!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of deciy16 in reverse (adjoint) mode:
!   gradient     of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DECIY16_B(ty, tyb, uy, uyb, cfi6y, csi6y, cwi6y, nx, nym, ny&
&  , nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE dericey6_m 
  USE paramy_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, ny, nym, nz, npaire
  REAL*8, DIMENSION(nx, nz, ny) :: ty
  REAL*8, DIMENSION(nx, nz, ny) :: tyb
  REAL*8, DIMENSION(nx, nz, nym) :: uy
  REAL*8, DIMENSION(nx, nz, nym) :: uyb
  REAL*8, DIMENSION(ny) :: cfi6y, csi6y, cwi6y
!
  INTEGER :: i, j, k
!
  IF (npaire .EQ. 1) THEN
    DO j=1,ny-1,1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j+1) = tyb(i, k, j+1) - cwi6y(j)*cfi6y(j)*tyb(i, k, &
&            j)
          tyb(i, k, j) = cwi6y(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, ny) = cwi6y(ny)*tyb(i, k, ny)
      END DO
    END DO
    DO j=ny,2,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j-1) = tyb(i, k, j-1) - csi6y(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    uyb = 0.0_8
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, ny) = 0.0_8
        uyb(i, k, ny-1) = uyb(i, k, ny-1) + (bciy6+aciy6)*tyb(i, k, ny-1&
&          )
        uyb(i, k, ny-2) = uyb(i, k, ny-2) - aciy6*tyb(i, k, ny-1)
        uyb(i, k, ny-3) = uyb(i, k, ny-3) - bciy6*tyb(i, k, ny-1)
        tyb(i, k, ny-1) = 0.0_8
      END DO
    END DO
    DO j=ny-2,3,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          uyb(i, k, j) = uyb(i, k, j) + aciy6*tyb(i, k, j)
          uyb(i, k, j-1) = uyb(i, k, j-1) - aciy6*tyb(i, k, j)
          uyb(i, k, j+1) = uyb(i, k, j+1) + bciy6*tyb(i, k, j)
          uyb(i, k, j-2) = uyb(i, k, j-2) - bciy6*tyb(i, k, j)
          tyb(i, k, j) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, 2) = uyb(i, k, 2) + aciy6*tyb(i, k, 2)
        uyb(i, k, 1) = uyb(i, k, 1) + (-bciy6-aciy6)*tyb(i, k, 2)
        uyb(i, k, 3) = uyb(i, k, 3) + bciy6*tyb(i, k, 2)
        tyb(i, k, 2) = 0.0_8
        tyb(i, k, 1) = 0.0_8
      END DO
    END DO
  ELSE
    uyb = 0.0_8
  END IF
!
END SUBROUTINE DECIY16_B
