!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of deciy6 in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DECIY6_D(ty, tyd, uy, uyd, cfi6y, csi6y, cwi6y, nx, nym, ny, &
&  nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramy_m
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, ny, nym, nz, npaire
  REAL*8, DIMENSION(nx, ny, nz) :: ty
  REAL*8, DIMENSION(nx, ny, nz) :: tyd
  REAL*8, DIMENSION(nx, nym, nz) :: uy
  REAL*8, DIMENSION(nx, nym, nz) :: uyd
  REAL*8, DIMENSION(nx, nz, ny) :: ry
  REAL*8, DIMENSION(nx, nz, ny) :: ryd
  REAL*8, DIMENSION(nx, nz, nym) :: di
  REAL*8, DIMENSION(nx, nz, nym) :: did
  REAL*8, DIMENSION(ny) :: cfi6y, csi6y, cwi6y
!
  INTEGER :: i, j, k
  did = 0.0_8
!
  DO k=1,nz
    DO j=1,nym
      DO i=1,nx
        did(i, k, j) = uyd(i, j, k)
        di(i, k, j) = uy(i, j, k)
      END DO
    END DO
  END DO
! 
  CALL DECIY16_D(ry, ryd, di, did, cfi6y, csi6y, cwi6y, nx, nym, ny, nz&
&           , npaire)
  tyd = 0.0_8
!
  DO k=1,nz
    DO j=1,ny
      DO i=1,nx
        tyd(i, j, k) = yly*ryd(i, k, j)
        ty(i, j, k) = ry(i, k, j)*yly
      END DO
    END DO
  END DO
!
  RETURN
END SUBROUTINE DECIY6_D
