!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of deciy6 in reverse (adjoint) mode:
!   gradient     of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DECIY6_B(ty, tyb, uy, uyb, cfi6y, csi6y, cwi6y, nx, nym, ny, &
&  nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramy_m
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, ny, nym, nz, npaire
  REAL*8, DIMENSION(nx, ny, nz) :: ty
  REAL*8, DIMENSION(nx, ny, nz) :: tyb
  REAL*8, DIMENSION(nx, nym, nz) :: uy
  REAL*8, DIMENSION(nx, nym, nz) :: uyb
  REAL*8, DIMENSION(nx, nz, ny) :: ry
  REAL*8, DIMENSION(nx, nz, ny) :: ryb
  REAL*8, DIMENSION(nx, nz, nym) :: di
  REAL*8, DIMENSION(nx, nz, nym) :: dib
  REAL*8, DIMENSION(ny) :: cfi6y, csi6y, cwi6y
!
  INTEGER :: i, j, k
!
  ryb = 0.0_8
  DO k=nz,1,-1
    DO j=ny,1,-1
      DO i=nx,1,-1
        ryb(i, k, j) = ryb(i, k, j) + yly*tyb(i, j, k)
        tyb(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  CALL DECIY16_B(ry, ryb, di, dib, cfi6y, csi6y, cwi6y, nx, nym, ny, nz&
&           , npaire)
  uyb = 0.0_8
  DO k=nz,1,-1
    DO j=nym,1,-1
      DO i=nx,1,-1
        uyb(i, j, k) = uyb(i, j, k) + dib(i, k, j)
        dib(i, k, j) = 0.0_8
      END DO
    END DO
  END DO
!
END SUBROUTINE DECIY6_B
