!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of deci6 in reverse (adjoint) mode:
!   gradient     of useful results: tx
!   with respect to varying inputs: ux
!
!********************************************************************
!
SUBROUTINE DECI6_B(tx, txb, ux, uxb, cfi6, csi6, cwi6, nxm, nx, ny, nz, &
&  npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramx_m 
  USE dericex6_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, nxm, ny, nz, npaire
  REAL*8, DIMENSION(nx, ny, nz) :: tx
  REAL*8, DIMENSION(nx, ny, nz) :: txb
  REAL*8, DIMENSION(nxm, ny, nz) :: ux
  REAL*8, DIMENSION(nxm, ny, nz) :: uxb
  REAL*8, DIMENSION(nx) :: cfi6, csi6, cwi6
!
  INTEGER :: i, j, k
!
  IF (npaire .EQ. 1) THEN
    DO i=1,nx-1,1
      DO k=nz,1,-1
        DO j=ny,1,-1
          txb(i+1, j, k) = txb(i+1, j, k) - cwi6(i)*cfi6(i)*txb(i, j, k)
          txb(i, j, k) = cwi6(i)*txb(i, j, k)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO j=ny,1,-1
        txb(nx, j, k) = cwi6(nx)*txb(nx, j, k)
      END DO
    END DO
    DO i=nx,2,-1
      DO k=nz,1,-1
        DO j=ny,1,-1
          txb(i-1, j, k) = txb(i-1, j, k) - csi6(i)*txb(i, j, k)
        END DO
      END DO
    END DO
    uxb = 0.0_8
    DO k=nz,1,-1
      DO j=ny,1,-1
        txb(nx, j, k) = 0.0_8
        uxb(nx-1, j, k) = uxb(nx-1, j, k) + (bcix6+acix6)*txb(nx-1, j, k&
&          )
        uxb(nx-2, j, k) = uxb(nx-2, j, k) - acix6*txb(nx-1, j, k)
        uxb(nx-3, j, k) = uxb(nx-3, j, k) - bcix6*txb(nx-1, j, k)
        txb(nx-1, j, k) = 0.0_8
      END DO
    END DO
    DO i=nx-2,3,-1
      DO k=nz,1,-1
        DO j=ny,1,-1
          uxb(i, j, k) = uxb(i, j, k) + acix6*txb(i, j, k)
          uxb(i-1, j, k) = uxb(i-1, j, k) - acix6*txb(i, j, k)
          uxb(i+1, j, k) = uxb(i+1, j, k) + bcix6*txb(i, j, k)
          uxb(i-2, j, k) = uxb(i-2, j, k) - bcix6*txb(i, j, k)
          txb(i, j, k) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO j=ny,1,-1
        uxb(2, j, k) = uxb(2, j, k) + acix6*txb(2, j, k)
        uxb(1, j, k) = uxb(1, j, k) + (-bcix6-acix6)*txb(2, j, k)
        uxb(3, j, k) = uxb(3, j, k) + bcix6*txb(2, j, k)
        txb(2, j, k) = 0.0_8
        txb(1, j, k) = 0.0_8
      END DO
    END DO
  ELSE
    uxb = 0.0_8
  END IF
!
END SUBROUTINE DECI6_B
