!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of decx6 in forward (tangent) mode:
!   variations   of useful results: tx
!   with respect to varying inputs: ux
!
!********************************************************************
!
SUBROUTINE DECX6_D(tx, txd, ux, uxd, cfx6, csx6, cwx6, nx, nxm, ny, nym&
&  , nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramx_m 
  USE dericex6_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx
  INTEGER, INTENT(IN) :: nxm
  INTEGER :: ny
  INTEGER, INTENT(IN) :: nym
  INTEGER, INTENT(IN) :: nz
  INTEGER, INTENT(IN) :: npaire
  REAL, INTENT(INOUT) :: tx(nxm, nym, nz)
  REAL, INTENT(INOUT) :: txd(nxm, nym, nz)
  REAL, INTENT(IN) :: ux(nx, nym, nz)
  REAL, INTENT(IN) :: uxd(nx, nym, nz)
  REAL, INTENT(IN) :: cfx6(nxm)
  REAL, INTENT(IN) :: csx6(nxm)
  REAL, INTENT(IN) :: cwx6(nxm)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
!-----------------------------------------------
!
  IF (npaire .EQ. 1) THEN
    txd = 0.0
    DO k=1,nz
      DO j=1,nym
        txd(1, j, k) = acix6*(uxd(2, j, k)-uxd(1, j, k)) + bcix6*(uxd(3&
&          , j, k)-uxd(2, j, k))
        tx(1, j, k) = acix6*(ux(2, j, k)-ux(1, j, k)) + bcix6*(ux(3, j, &
&          k)-ux(2, j, k))
        txd(2, j, k) = acix6*(uxd(3, j, k)-uxd(2, j, k)) + bcix6*(uxd(4&
&          , j, k)-uxd(1, j, k))
        tx(2, j, k) = acix6*(ux(3, j, k)-ux(2, j, k)) + bcix6*(ux(4, j, &
&          k)-ux(1, j, k))
      END DO
    END DO
    DO i=3,nxm-2
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = acix6*(uxd(i+1, j, k)-uxd(i, j, k)) + bcix6*(&
&            uxd(i+2, j, k)-uxd(i-1, j, k))
          tx(i, j, k) = acix6*(ux(i+1, j, k)-ux(i, j, k)) + bcix6*(ux(i+&
&            2, j, k)-ux(i-1, j, k))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,nym
        txd(nxm-1, j, k) = acix6*(uxd(nxm, j, k)-uxd(nxm-1, j, k)) + &
&          bcix6*(uxd(nx, j, k)-uxd(nxm-2, j, k))
        tx(nxm-1, j, k) = acix6*(ux(nxm, j, k)-ux(nxm-1, j, k)) + bcix6*&
&          (ux(nx, j, k)-ux(nxm-2, j, k))
        txd(nxm, j, k) = acix6*(uxd(nx, j, k)-uxd(nxm, j, k)) + bcix6*(&
&          uxd(nxm, j, k)-uxd(nxm-1, j, k))
        tx(nxm, j, k) = acix6*(ux(nx, j, k)-ux(nxm, j, k)) + bcix6*(ux(&
&          nxm, j, k)-ux(nxm-1, j, k))
      END DO
    END DO
    DO i=2,nxm
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = txd(i, j, k) - csx6(i)*txd(i-1, j, k)
          tx(i, j, k) = tx(i, j, k) - tx(i-1, j, k)*csx6(i)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,nym
        txd(nxm, j, k) = cwx6(nxm)*txd(nxm, j, k)
        tx(nxm, j, k) = tx(nxm, j, k)*cwx6(nxm)
      END DO
    END DO
    DO i=nxm-1,1,-1
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = cwx6(i)*(txd(i, j, k)-cfx6(i)*txd(i+1, j, k))
          tx(i, j, k) = (tx(i, j, k)-cfx6(i)*tx(i+1, j, k))*cwx6(i)
        END DO
      END DO
    END DO
  ELSE
    txd = 0.0
  END IF
  IF (npaire .EQ. 0) THEN
    DO k=1,nz
      DO j=1,nym
        txd(1, j, k) = acix6*(uxd(2, j, k)-uxd(1, j, k)) + bcix6*(uxd(3&
&          , j, k)-2.*uxd(1, j, k)+uxd(2, j, k))
        tx(1, j, k) = acix6*(ux(2, j, k)-ux(1, j, k)) + bcix6*(ux(3, j, &
&          k)-2.*ux(1, j, k)+ux(2, j, k))
        txd(2, j, k) = acix6*(uxd(3, j, k)-uxd(2, j, k)) + bcix6*(uxd(4&
&          , j, k)-uxd(1, j, k))
        tx(2, j, k) = acix6*(ux(3, j, k)-ux(2, j, k)) + bcix6*(ux(4, j, &
&          k)-ux(1, j, k))
      END DO
    END DO
    DO i=3,nxm-2
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = acix6*(uxd(i+1, j, k)-uxd(i, j, k)) + bcix6*(&
&            uxd(i+2, j, k)-uxd(i-1, j, k))
          tx(i, j, k) = acix6*(ux(i+1, j, k)-ux(i, j, k)) + bcix6*(ux(i+&
&            2, j, k)-ux(i-1, j, k))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,nym
        txd(nxm-1, j, k) = acix6*(uxd(nxm, j, k)-uxd(nxm-1, j, k)) + &
&          bcix6*(uxd(nx, j, k)-uxd(nxm-2, j, k))
        tx(nxm-1, j, k) = acix6*(ux(nxm, j, k)-ux(nxm-1, j, k)) + bcix6*&
&          (ux(nx, j, k)-ux(nxm-2, j, k))
        txd(nxm, j, k) = acix6*(uxd(nx, j, k)-uxd(nxm, j, k)) + bcix6*(&
&          2.*uxd(nx, j, k)-uxd(nxm, j, k)-uxd(nxm-1, j, k))
        tx(nxm, j, k) = acix6*(ux(nx, j, k)-ux(nxm, j, k)) + bcix6*(2.*&
&          ux(nx, j, k)-ux(nxm, j, k)-ux(nxm-1, j, k))
      END DO
    END DO
    DO i=2,nxm
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = txd(i, j, k) - csx6(i)*txd(i-1, j, k)
          tx(i, j, k) = tx(i, j, k) - tx(i-1, j, k)*csx6(i)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,nym
        txd(nxm, j, k) = cwx6(nxm)*txd(nxm, j, k)
        tx(nxm, j, k) = tx(nxm, j, k)*cwx6(nxm)
      END DO
    END DO
    DO i=nxm-1,1,-1
      DO k=1,nz
        DO j=1,nym
          txd(i, j, k) = cwx6(i)*(txd(i, j, k)-cfx6(i)*txd(i+1, j, k))
          tx(i, j, k) = (tx(i, j, k)-cfx6(i)*tx(i+1, j, k))*cwx6(i)
        END DO
      END DO
    END DO
  END IF
END SUBROUTINE DECX6_D
