!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of decy16 in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DECY16_D(ty, tyd, uy, uyd, cfy6, csy6, cwy6, nx, nxm, ny, nym&
&  , nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE dericey6_m 
  USE paramy_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, nxm, ny, nym, nz, npaire
  REAL*8, INTENT(INOUT) :: ty(nxm, nz, nym)
  REAL*8, INTENT(INOUT) :: tyd(nxm, nz, nym)
  REAL*8, INTENT(IN) :: uy(nxm, nz, ny)
  REAL*8, INTENT(IN) :: uyd(nxm, nz, ny)
  REAL*8, INTENT(IN) :: cfy6(nym)
  REAL*8, INTENT(IN) :: csy6(nym)
  REAL*8, INTENT(IN) :: cwy6(nym)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, i, j
!-----------------------------------------------
!
!********************************************************************
!
  IF (npaire .EQ. 0) THEN
    tyd = 0.0_8
    DO k=1,nz
      DO i=1,nxm
        tyd(i, k, 1) = aciy6*(uyd(i, k, 2)-uyd(i, k, 1)) + bciy6*(uyd(i&
&          , k, 3)-2.*uyd(i, k, 1)+uyd(i, k, 2))
        ty(i, k, 1) = aciy6*(uy(i, k, 2)-uy(i, k, 1)) + bciy6*(uy(i, k, &
&          3)-2.*uy(i, k, 1)+uy(i, k, 2))
        tyd(i, k, 2) = aciy6*(uyd(i, k, 3)-uyd(i, k, 2)) + bciy6*(uyd(i&
&          , k, 4)-uyd(i, k, 1))
        ty(i, k, 2) = aciy6*(uy(i, k, 3)-uy(i, k, 2)) + bciy6*(uy(i, k, &
&          4)-uy(i, k, 1))
      END DO
    END DO
    DO j=3,nym-2
      DO k=1,nz
        DO i=1,nxm
          tyd(i, j, k) = aciy6*(uyd(i, k, j+1)-uyd(i, k, j)) + bciy6*(&
&            uyd(i, k, j+2)-uyd(i, k, j-1))
          ty(i, j, k) = aciy6*(uy(i, k, j+1)-uy(i, k, j)) + bciy6*(uy(i&
&            , k, j+2)-uy(i, k, j-1))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nxm
        tyd(i, k, nym-1) = aciy6*(uyd(i, k, nym)-uyd(i, k, nym-1)) + &
&          bciy6*(uyd(i, k, ny)-uyd(i, k, nym-2))
        ty(i, k, nym-1) = aciy6*(uy(i, k, nym)-uy(i, k, nym-1)) + bciy6*&
&          (uy(i, k, ny)-uy(i, k, nym-2))
        tyd(i, k, nym) = aciy6*(uyd(i, k, ny)-uyd(i, k, nym)) + bciy6*(&
&          2.*uyd(i, k, ny)-uyd(i, k, nym)-uyd(i, k, nym-1))
        ty(i, k, nym) = aciy6*(uy(i, k, ny)-uy(i, k, nym)) + bciy6*(2.*&
&          uy(i, k, ny)-uy(i, k, nym)-uy(i, k, nym-1))
      END DO
    END DO
    DO j=2,nym
      DO k=1,nz
        DO i=1,nxm
          tyd(i, k, j) = tyd(i, k, j) - csy6(j)*tyd(i, k, j-1)
          ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*csy6(j)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nxm
        tyd(i, k, nym) = cwy6(nym)*tyd(i, k, nym)
        ty(i, k, nym) = ty(i, k, nym)*cwy6(nym)
      END DO
    END DO
    DO j=nym-1,1,-1
      DO k=1,nz
        DO i=1,nxm
          tyd(i, k, j) = cwy6(j)*(tyd(i, k, j)-cfy6(j)*tyd(i, k, j+1))
          ty(i, k, j) = (ty(i, k, j)-cfy6(j)*ty(i, k, j+1))*cwy6(j)
        END DO
      END DO
    END DO
  ELSE
    tyd = 0.0_8
  END IF
!
  RETURN
END SUBROUTINE DECY16_D
