!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of derx in forward (tangent) mode:
!   variations   of useful results: tx
!   with respect to varying inputs: ux
!********************************************************************
!
SUBROUTINE DERX_D(tx, txd, ux, uxd, ffx, fsx, fwx, nx, ny, nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramx_m
  USE derivex_m
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx
  INTEGER, INTENT(IN) :: ny
  INTEGER, INTENT(IN) :: nz
  INTEGER, INTENT(IN) :: npaire
  REAL, INTENT(INOUT) :: tx(nx, ny, nz)
  REAL, INTENT(INOUT) :: txd(nx, ny, nz)
  REAL*8, INTENT(IN) :: ux(nx, ny, nz)
  REAL*8, INTENT(IN) :: uxd(nx, ny, nz)
  REAL*8, INTENT(IN) :: ffx(nx)
  REAL*8, INTENT(IN) :: fsx(nx)
  REAL*8, INTENT(IN) :: fwx(nx)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
!-----------------------------------------------
!
!********************************************************************
!
  IF (nclx .EQ. 2) THEN
    txd = 0.0
    DO k=1,nz
      DO j=1,ny
        txd(1, j, k) = af1x*uxd(1, j, k) + bf1x*uxd(2, j, k) + cf1x*uxd(&
&          3, j, k)
        tx(1, j, k) = af1x*ux(1, j, k) + bf1x*ux(2, j, k) + cf1x*ux(3, j&
&          , k)
        txd(2, j, k) = af2x*(uxd(3, j, k)-uxd(1, j, k))
        tx(2, j, k) = af2x*(ux(3, j, k)-ux(1, j, k))
      END DO
    END DO
    DO i=3,nx-2
      DO k=1,nz
        DO j=1,ny
          txd(i, j, k) = afix*(uxd(i+1, j, k)-uxd(i-1, j, k)) + bfix*(&
&            uxd(i+2, j, k)-uxd(i-2, j, k))
          tx(i, j, k) = afix*(ux(i+1, j, k)-ux(i-1, j, k)) + bfix*(ux(i+&
&            2, j, k)-ux(i-2, j, k))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,ny
        txd(nx-1, j, k) = afmx*(uxd(nx, j, k)-uxd(nx-2, j, k))
        tx(nx-1, j, k) = afmx*(ux(nx, j, k)-ux(nx-2, j, k))
        txd(nx, j, k) = -(afnx*uxd(nx, j, k)) - bfnx*uxd(nx-1, j, k) - &
&          cfnx*uxd(nx-2, j, k)
        tx(nx, j, k) = -(afnx*ux(nx, j, k)) - bfnx*ux(nx-1, j, k) - cfnx&
&          *ux(nx-2, j, k)
      END DO
    END DO
    DO i=2,nx
      DO k=1,nz
        DO j=1,ny
          txd(i, j, k) = txd(i, j, k) - fsx(i)*txd(i-1, j, k)
          tx(i, j, k) = tx(i, j, k) - tx(i-1, j, k)*fsx(i)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO j=1,ny
        txd(nx, j, k) = fwx(nx)*txd(nx, j, k)
        tx(nx, j, k) = tx(nx, j, k)*fwx(nx)
      END DO
    END DO
    DO i=nx-1,1,-1
      DO k=1,nz
        DO j=1,ny
          txd(i, j, k) = fwx(i)*(txd(i, j, k)-ffx(i)*txd(i+1, j, k))
          tx(i, j, k) = (tx(i, j, k)-ffx(i)*tx(i+1, j, k))*fwx(i)
        END DO
      END DO
    END DO
  ELSE
    txd = 0.0
  END IF
END SUBROUTINE DERX_D
