!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of deryy in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DERYY_D(ty, tyd, uy, uyd, sfy, ssy, swy, nx, ny, nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramy_m 
  USE derivey_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx
  INTEGER, INTENT(IN) :: ny
  INTEGER, INTENT(IN) :: nz
  INTEGER, INTENT(IN) :: npaire
  REAL*8, INTENT(INOUT) :: ty(nx, nz, ny)
  REAL*8, INTENT(INOUT) :: tyd(nx, nz, ny)
  REAL*8, INTENT(IN) :: uy(nx, nz, ny)
  REAL*8, INTENT(IN) :: uyd(nx, nz, ny)
  REAL*8, INTENT(IN) :: sfy(ny)
  REAL*8, INTENT(IN) :: ssy(ny)
  REAL*8, INTENT(IN) :: swy(ny)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
!-----------------------------------------------
!
!********************************************************************
!
  IF (ncly .EQ. 1) THEN
    IF (npaire .EQ. 1) THEN
      tyd = 0.0_8
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, 1) = asjy*(2*uyd(i, k, 2)-2*uyd(i, k, 1)) + bsjy*(2*&
&            uyd(i, k, 3)-2*uyd(i, k, 1))
          ty(i, k, 1) = asjy*(uy(i, k, 2)-uy(i, k, 1)-uy(i, k, 1)+uy(i, &
&            k, 2)) + bsjy*(uy(i, k, 3)-uy(i, k, 1)-uy(i, k, 1)+uy(i, k, &
&            3))
          tyd(i, k, 2) = asjy*(uyd(i, k, 3)-2*uyd(i, k, 2)+uyd(i, k, 1))&
&            + bsjy*(uyd(i, k, 4)-uyd(i, k, 2))
          ty(i, k, 2) = asjy*(uy(i, k, 3)-uy(i, k, 2)-uy(i, k, 2)+uy(i, &
&            k, 1)) + bsjy*(uy(i, k, 4)-uy(i, k, 2)-uy(i, k, 2)+uy(i, k, &
&            2))
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          DO j=3,ny-2
            tyd(i, k, j) = asjy*(uyd(i, k, j+1)-2*uyd(i, k, j)+uyd(i, k&
&              , j-1)) + bsjy*(uyd(i, k, j+2)-2*uyd(i, k, j)+uyd(i, k, j-&
&              2))
            ty(i, k, j) = asjy*(uy(i, k, j+1)-uy(i, k, j)-uy(i, k, j)+uy&
&              (i, k, j-1)) + bsjy*(uy(i, k, j+2)-uy(i, k, j)-uy(i, k, j)&
&              +uy(i, k, j-2))
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny-1) = asjy*(uyd(i, k, ny)-2*uyd(i, k, ny-1)+uyd(i&
&            , k, ny-2)) + bsjy*(uyd(i, k, ny-3)-uyd(i, k, ny-1))
          ty(i, k, ny-1) = asjy*(uy(i, k, ny)-uy(i, k, ny-1)-uy(i, k, ny&
&            -1)+uy(i, k, ny-2)) + bsjy*(uy(i, k, ny-1)-uy(i, k, ny-1)-uy&
&            (i, k, ny-1)+uy(i, k, ny-3))
          tyd(i, k, ny) = asjy*(2*uyd(i, k, ny-1)-2*uyd(i, k, ny)) + &
&            bsjy*(2*uyd(i, k, ny-2)-2*uyd(i, k, ny))
          ty(i, k, ny) = asjy*(uy(i, k, ny-1)-uy(i, k, ny)-uy(i, k, ny)+&
&            uy(i, k, ny-1)) + bsjy*(uy(i, k, ny-2)-uy(i, k, ny)-uy(i, k&
&            , ny)+uy(i, k, ny-2))
        END DO
      END DO
      DO j=2,ny
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = tyd(i, k, j) - ssy(j)*tyd(i, k, j-1)
            ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*ssy(j)
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny) = swy(ny)*tyd(i, k, ny)
          ty(i, k, ny) = ty(i, k, ny)*swy(ny)
        END DO
      END DO
      DO j=ny-1,1,-1
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = swy(j)*(tyd(i, k, j)-sfy(j)*tyd(i, k, j+1))
            ty(i, k, j) = (ty(i, k, j)-sfy(j)*ty(i, k, j+1))*swy(j)
          END DO
        END DO
      END DO
    ELSE
      tyd = 0.0_8
    END IF
    IF (npaire .EQ. 0) THEN
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, 1) = 0.0_8
          ty(i, k, 1) = 0.
          tyd(i, k, 2) = asjy*(uyd(i, k, 3)-2*uyd(i, k, 2)+uyd(i, k, 1))&
&            + bsjy*(uyd(i, k, 4)-3*uyd(i, k, 2))
          ty(i, k, 2) = asjy*(uy(i, k, 3)-uy(i, k, 2)-uy(i, k, 2)+uy(i, &
&            k, 1)) + bsjy*(uy(i, k, 4)-uy(i, k, 2)-uy(i, k, 2)-uy(i, k, &
&            2))
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          DO j=3,ny-2
            tyd(i, k, j) = asjy*(uyd(i, k, j+1)-2*uyd(i, k, j)+uyd(i, k&
&              , j-1)) + bsjy*(uyd(i, k, j+2)-2*uyd(i, k, j)+uyd(i, k, j-&
&              2))
            ty(i, k, j) = asjy*(uy(i, k, j+1)-uy(i, k, j)-uy(i, k, j)+uy&
&              (i, k, j-1)) + bsjy*(uy(i, k, j+2)-uy(i, k, j)-uy(i, k, j)&
&              +uy(i, k, j-2))
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny-1) = asjy*(uyd(i, k, ny)-2*uyd(i, k, ny-1)+uyd(i&
&            , k, ny-2)) + bsjy*(uyd(i, k, ny-3)-3*uyd(i, k, ny-1))
          ty(i, k, ny-1) = asjy*(uy(i, k, ny)-uy(i, k, ny-1)-uy(i, k, ny&
&            -1)+uy(i, k, ny-2)) + bsjy*(-uy(i, k, ny-1)-uy(i, k, ny-1)-&
&            uy(i, k, ny-1)+uy(i, k, ny-3))
          tyd(i, k, ny) = 0.0_8
          ty(i, k, ny) = 0.
        END DO
      END DO
      DO j=2,ny
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = tyd(i, k, j) - ssy(j)*tyd(i, k, j-1)
            ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*ssy(j)
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny) = swy(ny)*tyd(i, k, ny)
          ty(i, k, ny) = ty(i, k, ny)*swy(ny)
        END DO
      END DO
      DO j=ny-1,1,-1
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = swy(j)*(tyd(i, k, j)-sfy(j)*tyd(i, k, j+1))
            ty(i, k, j) = (ty(i, k, j)-sfy(j)*ty(i, k, j+1))*swy(j)
          END DO
        END DO
      END DO
    END IF
  ELSE
    tyd = 0.0_8
  END IF
!
  RETURN
END SUBROUTINE DERYY_D
