!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of dery in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DERY_D(ty, tyd, uy, uyd, ffy, fsy, fwy, nx, ny, nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramy_m 
  USE derivey_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx
  INTEGER, INTENT(IN) :: ny
  INTEGER, INTENT(IN) :: nz
  INTEGER, INTENT(IN) :: npaire
  REAL*8, INTENT(INOUT) :: ty(nx, nz, ny)
  REAL*8, INTENT(INOUT) :: tyd(nx, nz, ny)
  REAL*8, INTENT(IN) :: uy(nx, nz, ny)
  REAL*8, INTENT(IN) :: uyd(nx, nz, ny)
  REAL*8, INTENT(IN) :: ffy(ny)
  REAL*8, INTENT(IN) :: fsy(ny)
  REAL*8, INTENT(IN) :: fwy(ny)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
!-----------------------------------------------
!
!********************************************************************
!
  IF (ncly .EQ. 1) THEN
    IF (npaire .EQ. 1) THEN
      tyd = 0.0_8
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, 1) = 0.0_8
          ty(i, k, 1) = 0.
          tyd(i, k, 2) = afjy*(uyd(i, k, 3)-uyd(i, k, 1)) + bfjy*(uyd(i&
&            , k, 4)-uyd(i, k, 2))
          ty(i, k, 2) = afjy*(uy(i, k, 3)-uy(i, k, 1)) + bfjy*(uy(i, k, &
&            4)-uy(i, k, 2))
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          DO j=3,ny-2
            tyd(i, k, j) = afjy*(uyd(i, k, j+1)-uyd(i, k, j-1)) + bfjy*(&
&              uyd(i, k, j+2)-uyd(i, k, j-2))
            ty(i, k, j) = afjy*(uy(i, k, j+1)-uy(i, k, j-1)) + bfjy*(uy(&
&              i, k, j+2)-uy(i, k, j-2))
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny-1) = afjy*(uyd(i, k, ny)-uyd(i, k, ny-2)) + bfjy*&
&            (uyd(i, k, ny-1)-uyd(i, k, ny-3))
          ty(i, k, ny-1) = afjy*(uy(i, k, ny)-uy(i, k, ny-2)) + bfjy*(uy&
&            (i, k, ny-1)-uy(i, k, ny-3))
          tyd(i, k, ny) = 0.0_8
          ty(i, k, ny) = 0.
        END DO
      END DO
      DO j=2,ny
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = tyd(i, k, j) - fsy(j)*tyd(i, k, j-1)
            ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*fsy(j)
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny) = fwy(ny)*tyd(i, k, ny)
          ty(i, k, ny) = ty(i, k, ny)*fwy(ny)
        END DO
      END DO
      DO j=ny-1,1,-1
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = fwy(j)*(tyd(i, k, j)-ffy(j)*tyd(i, k, j+1))
            ty(i, k, j) = (ty(i, k, j)-ffy(j)*ty(i, k, j+1))*fwy(j)
          END DO
        END DO
      END DO
    ELSE
      tyd = 0.0_8
    END IF
    IF (npaire .EQ. 0) THEN
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, 1) = afjy*2*uyd(i, k, 2) + bfjy*2*uyd(i, k, 3)
          ty(i, k, 1) = afjy*(uy(i, k, 2)+uy(i, k, 2)) + bfjy*(uy(i, k, &
&            3)+uy(i, k, 3))
          tyd(i, k, 2) = afjy*(uyd(i, k, 3)-uyd(i, k, 1)) + bfjy*(uyd(i&
&            , k, 4)+uyd(i, k, 2))
          ty(i, k, 2) = afjy*(uy(i, k, 3)-uy(i, k, 1)) + bfjy*(uy(i, k, &
&            4)+uy(i, k, 2))
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          DO j=3,ny-2
            tyd(i, k, j) = afjy*(uyd(i, k, j+1)-uyd(i, k, j-1)) + bfjy*(&
&              uyd(i, k, j+2)-uyd(i, k, j-2))
            ty(i, k, j) = afjy*(uy(i, k, j+1)-uy(i, k, j-1)) + bfjy*(uy(&
&              i, k, j+2)-uy(i, k, j-2))
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny-1) = afjy*(uyd(i, k, ny)-uyd(i, k, ny-2)) + bfjy*&
&            (-uyd(i, k, ny-1)-uyd(i, k, ny-3))
          ty(i, k, ny-1) = afjy*(uy(i, k, ny)-uy(i, k, ny-2)) + bfjy*(-&
&            uy(i, k, ny-1)-uy(i, k, ny-3))
          tyd(i, k, ny) = -(afjy*2*uyd(i, k, ny-1)) - bfjy*2*uyd(i, k, &
&            ny-2)
          ty(i, k, ny) = afjy*(-uy(i, k, ny-1)-uy(i, k, ny-1)) + bfjy*(-&
&            uy(i, k, ny-2)-uy(i, k, ny-2))
        END DO
      END DO
      DO j=2,ny
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = tyd(i, k, j) - fsy(j)*tyd(i, k, j-1)
            ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*fsy(j)
          END DO
        END DO
      END DO
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, ny) = fwy(ny)*tyd(i, k, ny)
          ty(i, k, ny) = ty(i, k, ny)*fwy(ny)
        END DO
      END DO
      DO j=ny-1,1,-1
        DO k=1,nz
          DO i=1,nx
            tyd(i, k, j) = fwy(j)*(tyd(i, k, j)-ffy(j)*tyd(i, k, j+1))
            ty(i, k, j) = (ty(i, k, j)-ffy(j)*ty(i, k, j+1))*fwy(j)
          END DO
        END DO
      END DO
    END IF
  ELSE
    tyd = 0.0_8
  END IF
!
!********************STRET STRET************************
  DO k=1,nz
    DO j=1,ny
      DO i=1,nx
        tyd(i, j, k) = yly*tyd(i, k, j)
        ty(i, j, k) = ty(i, k, j)*yly
      END DO
    END DO
  END DO
!*******************************************************
!
  RETURN
END SUBROUTINE DERY_D
