!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of dery in reverse (adjoint) mode:
!   gradient     of useful results: ty uy
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE DERY_R_B(ty, tyb, uy, uyb, ffy, fsy, fwy, nx, ny, nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramy_m 
  USE derivey_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx
  INTEGER, INTENT(IN) :: ny
  INTEGER, INTENT(IN) :: nz
  INTEGER, INTENT(IN) :: npaire
  REAL*8, INTENT(INOUT) :: ty(nx, nz, ny)
  REAL*8 :: tyb(nx, nz, ny)
  REAL*8, INTENT(IN) :: uy(nx, nz, ny)
  REAL*8 :: uyb(nx, nz, ny)
  REAL*8, INTENT(IN) :: ffy(ny)
  REAL*8, INTENT(IN) :: fsy(ny)
  REAL*8, INTENT(IN) :: fwy(ny)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
  REAL*8 :: tmp
  INTEGER :: branch
  REAL*8 :: tmpb
!-----------------------------------------------
!
!********************************************************************
!
  IF (ncly .EQ. 1) THEN
    IF (npaire .EQ. 1) THEN
      CALL PUSHINTEGER4(1)
    ELSE
      CALL PUSHINTEGER4(0)
    END IF
    IF (npaire .EQ. 0) THEN
      CALL PUSHINTEGER4(2)
    ELSE
      CALL PUSHINTEGER4(1)
    END IF
  ELSE
    CALL PUSHINTEGER4(0)
  END IF
  DO k=nz,1,-1
    DO j=ny,1,-1
      DO i=nx,1,-1
        tmpb = tyb(i, j, k)
        tyb(i, j, k) = 0.0_8
        tyb(i, k, j) = tyb(i, k, j) + ylyr*tmpb
      END DO
    END DO
  END DO
  CALL POPINTEGER4(branch)
  IF (branch .LT. 2) THEN
    IF (branch .LT. 1) GOTO 100
  ELSE
    DO j=1,ny-1,1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j+1) = tyb(i, k, j+1) - fwy(j)*ffy(j)*tyb(i, k, j)
          tyb(i, k, j) = fwy(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, ny) = fwy(ny)*tyb(i, k, ny)
      END DO
    END DO
    DO j=ny,2,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j-1) = tyb(i, k, j-1) - fsy(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, ny-1) = uyb(i, k, ny-1) - afjy*2*tyb(i, k, ny)
        uyb(i, k, ny-2) = uyb(i, k, ny-2) - bfjy*2*tyb(i, k, ny)
        tyb(i, k, ny) = 0.0_8
        uyb(i, k, ny) = uyb(i, k, ny) + afjy*tyb(i, k, ny-1)
        uyb(i, k, ny-2) = uyb(i, k, ny-2) - afjy*tyb(i, k, ny-1)
        uyb(i, k, ny-1) = uyb(i, k, ny-1) - bfjy*tyb(i, k, ny-1)
        uyb(i, k, ny-3) = uyb(i, k, ny-3) - bfjy*tyb(i, k, ny-1)
        tyb(i, k, ny-1) = 0.0_8
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        DO j=ny-2,3,-1
          uyb(i, k, j+1) = uyb(i, k, j+1) + afjy*tyb(i, k, j)
          uyb(i, k, j-1) = uyb(i, k, j-1) - afjy*tyb(i, k, j)
          uyb(i, k, j+2) = uyb(i, k, j+2) + bfjy*tyb(i, k, j)
          uyb(i, k, j-2) = uyb(i, k, j-2) - bfjy*tyb(i, k, j)
          tyb(i, k, j) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, 3) = uyb(i, k, 3) + afjy*tyb(i, k, 2)
        uyb(i, k, 1) = uyb(i, k, 1) - afjy*tyb(i, k, 2)
        uyb(i, k, 4) = uyb(i, k, 4) + bfjy*tyb(i, k, 2)
        uyb(i, k, 2) = uyb(i, k, 2) + bfjy*tyb(i, k, 2)
        tyb(i, k, 2) = 0.0_8
        uyb(i, k, 2) = uyb(i, k, 2) + afjy*2*tyb(i, k, 1)
        uyb(i, k, 3) = uyb(i, k, 3) + bfjy*2*tyb(i, k, 1)
        tyb(i, k, 1) = 0.0_8
      END DO
    END DO
  END IF
  CALL POPINTEGER4(branch)
  IF (.NOT.branch .LT. 1) THEN
    DO j=1,ny-1,1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j+1) = tyb(i, k, j+1) - fwy(j)*ffy(j)*tyb(i, k, j)
          tyb(i, k, j) = fwy(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, ny) = fwy(ny)*tyb(i, k, ny)
      END DO
    END DO
    DO j=ny,2,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j-1) = tyb(i, k, j-1) - fsy(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, ny) = 0.0_8
        uyb(i, k, ny) = uyb(i, k, ny) + afjy*tyb(i, k, ny-1)
        uyb(i, k, ny-2) = uyb(i, k, ny-2) - afjy*tyb(i, k, ny-1)
        uyb(i, k, ny-1) = uyb(i, k, ny-1) + bfjy*tyb(i, k, ny-1)
        uyb(i, k, ny-3) = uyb(i, k, ny-3) - bfjy*tyb(i, k, ny-1)
        tyb(i, k, ny-1) = 0.0_8
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        DO j=ny-2,3,-1
          uyb(i, k, j+1) = uyb(i, k, j+1) + afjy*tyb(i, k, j)
          uyb(i, k, j-1) = uyb(i, k, j-1) - afjy*tyb(i, k, j)
          uyb(i, k, j+2) = uyb(i, k, j+2) + bfjy*tyb(i, k, j)
          uyb(i, k, j-2) = uyb(i, k, j-2) - bfjy*tyb(i, k, j)
          tyb(i, k, j) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, 3) = uyb(i, k, 3) + afjy*tyb(i, k, 2)
        uyb(i, k, 1) = uyb(i, k, 1) - afjy*tyb(i, k, 2)
        uyb(i, k, 4) = uyb(i, k, 4) + bfjy*tyb(i, k, 2)
        uyb(i, k, 2) = uyb(i, k, 2) - bfjy*tyb(i, k, 2)
        tyb(i, k, 2) = 0.0_8
        tyb(i, k, 1) = 0.0_8
      END DO
    END DO
  END IF
 100 CONTINUE
END SUBROUTINE DERY_R_B
