!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion3 in reverse (adjoint) mode:
!   gradient     of useful results: ps2d3
!   with respect to varying inputs: ps2d2 ps2d3
!   RW status of diff variables: ps2d2:out ps2d3:in-out
!
!  Entrada: ps2d3b
!  Salida: ps2d2b
! 
!********************************************************************
!
SUBROUTINE FUNCION3_B(ps2d2b, ps2d3b, mx, my, nx, ny, nxm&
&  , nym)
!
  implicit none
!
  INTEGER :: i, j, mx, my, nx, ny, nxm, nym
!
  REAL*8, DIMENSION(mx, my) :: ps2d2, ps2d3
  REAL*8, DIMENSION(mx, my) :: ps2d2b, ps2d3b
  REAL*8, DIMENSION(mx, my) :: ur, ue, ur1, ue1
  REAL*8, DIMENSION(mx, my) :: urb, ueb, ur1b, ue1b
  REAL*8 :: xx1, xx2
  REAL*8 :: xx1b, xx2b
  REAL*8 :: pi
  REAL*8 :: tmp
  REAL*8 :: tmp0
  REAL*8 :: tmp1
  REAL*8 :: tmp2
  INTRINSIC COS
  INTRINSIC SIN
  REAL*8 :: tempb0
  REAL*8 :: tmpb
  REAL*8 :: tmp0b
  REAL*8 :: tempb
  REAL*8 :: tmp2b
  INTRINSIC ACOS
  INTRINSIC SQRT
  REAL*8 :: tmp1b
!
  pi = ACOS(-1.)
  DO j=ny,1,-1
    ps2d3b(1, j) = 2.*ps2d3b(1, j)
  END DO
  ue1b = 0.0_8
  ur1b = 0.0_8
  DO j=ny,1,-1
    DO i=nxm,1,-1
      xx1b = ps2d3b(i, j)
      xx2b = ps2d3b(i, j)
      ps2d3b(i, j) = 0.0_8
      tempb = SIN((i-1)*pi/(2.*nxm))*xx2b/2.
      ue1b(i, j) = ue1b(i, j) + tempb
      ue1b(nxm-i+2, j) = ue1b(nxm-i+2, j) - tempb
      tempb0 = COS((i-1)*pi/(2.*nxm))*xx1b/2.
      ur1b(i, j) = ur1b(i, j) + tempb0
      ur1b(nxm-i+2, j) = ur1b(nxm-i+2, j) + tempb0
    END DO
  END DO
  DO i=nxm,1,-1
    ue1b(i, 1) = 2.*ue1b(i, 1)
    ur1b(i, 1) = 2.*ur1b(i, 1)
  END DO
  DO j=ny,1,-1
    DO i=nxm/2,2,-1
      tmp2b = ue1b(i+nxm/2, j)
      ue1b(i+nxm/2, j) = 0.0_8
      ue1b(nxm/2-i+2, j) = ue1b(nxm/2-i+2, j) - tmp2b
    END DO
  END DO
  ueb = 0.0_8
  urb = 0.0_8
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      xx1b = ue1b(i, j)
      xx2b = ue1b(i, j)
      ue1b(i, j) = 0.0_8
      urb(i, nym-j+2) = urb(i, nym-j+2) + SIN((j-1)*pi/(2.*nym))*xx2b/2.
      ueb(i, nym-j+2) = ueb(i, nym-j+2) + COS((j-1)*pi/(2.*nym))*xx2b/2.
      ueb(i, j) = ueb(i, j) + COS((j-1)*pi/(2.*nym))*xx1b/2.
      urb(i, j) = urb(i, j) - SIN((j-1)*pi/(2.*nym))*xx1b/2.
    END DO
  END DO
  DO j=ny,1,-1
    DO i=nxm/2,2,-1
      tmp1b = ur1b(i+nxm/2, j)
      ur1b(i+nxm/2, j) = 0.0_8
      ur1b(nxm/2-i+2, j) = ur1b(nxm/2-i+2, j) + tmp1b
    END DO
  END DO
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      xx1b = ur1b(i, j)
      xx2b = ur1b(i, j)
      ur1b(i, j) = 0.0_8
      urb(i, nym-j+2) = urb(i, nym-j+2) + COS((j-1)*pi/(2.*nym))*xx2b/2.
      ueb(i, nym-j+2) = ueb(i, nym-j+2) - SIN((j-1)*pi/(2.*nym))*xx2b/2.
      urb(i, j) = urb(i, j) + COS((j-1)*pi/(2.*nym))*xx1b/2.
      ueb(i, j) = ueb(i, j) + SIN((j-1)*pi/(2.*nym))*xx1b/2.
    END DO
  END DO
  DO j=nym,1,-1
    DO i=nxm/2,2,-1
      tmp0b = ueb(i+nxm/2, j)
      ueb(i+nxm/2, j) = 0.0_8
      ueb(nxm/2-i+2, j) = ueb(nxm/2-i+2, j) - tmp0b
    END DO
  END DO
  ps2d2b = 0.0_8
  DO j=nym,1,-1
    ps2d2b(nx+1, j) = ps2d2b(nx+1, j) + ueb(nxm/2+1, j)
    ueb(nxm/2+1, j) = 0.0_8
  END DO
  DO j=nym,1,-1
    DO i=nxm/2,1,-1
      ps2d2b(2*i, j) = ps2d2b(2*i, j) + ueb(i, j)
      ueb(i, j) = 0.0_8
    END DO
  END DO
  DO j=nym,1,-1
    DO i=nxm/2,2,-1
      tmpb = urb(i+nxm/2, j)
      urb(i+nxm/2, j) = 0.0_8
      urb(nxm/2-i+2, j) = urb(nxm/2-i+2, j) + tmpb
    END DO
  END DO
  DO j=nym,1,-1
    ps2d2b(nxm+1, j) = ps2d2b(nxm+1, j) + urb(nxm/2+1, j)
    urb(nxm/2+1, j) = 0.0_8
  END DO
  DO j=nym,1,-1
    DO i=nxm/2,1,-1
      ps2d2b(2*i-1, j) = ps2d2b(2*i-1, j) + urb(i, j)
      urb(i, j) = 0.0_8
    END DO
  END DO
  DO j=my,1,-1
    DO i=mx,1,-1
      ps2d2b(i, j) = ps2d2b(i, j) + ps2d3b(i, j)
      ps2d3b(i, j) = 0.0_8
    END DO
  END DO
  DO i=nxm,3,-1
    DO j=my,1,-1
      ps2d2b(i, j) = ps2d2b(i, j)/SQRT(2.)
    END DO
  END DO
!
END SUBROUTINE FUNCION3_B
