!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion1 in forward (tangent) mode:
!   variations   of useful results: g8x g8y ps2d1 u8x u8y
!   with respect to varying inputs: bx1 by1 gx gy ux uy
!   RW status of diff variables: gx:in gy:in g8x:out g8y:out ux:in
!                uy:in bx1:in by1:in ps2d1:out u8x:out u8y:out
!
!  Entrada: ux, uy, gx, gy, bx1, by1, uxd, uyd, gxd, gyd, bx1d, by1d
!  Salida: u8xd, u8yd, g8xd, g8yd, ps2d1d
!  
!********************************************************************
!
SUBROUTINE FUNCION1_D(ux,uxd,uy,uyd,gx,gxd,gy,gyd,bx1,bx1d,by1,by1d,&
             u8x,u8xd,u8y,u8yd,g8x,g8xd,g8y,g8yd,ps2d1,ps2d1d,&
             ffx,fsx,fwx,ffy,fsy,fwy,&
             ffxp,fsxp,fwxp,&
             ffyp,fsyp,fwyp,&
             sfx,ssx,swx,sfy,ssy,swy,&
             sfxp,ssxp,swxp,&
             sfyp,ssyp,swyp,&
             cfx6,csx6,cwx6,&
             cfxp6,csxp6,cwxp6,&
             cifx6,cisx6,ciwx6,cifxp6,cisxp6,ciwxp6,&
             cfy6,csy6,cwy6,cfyp6,csyp6,cwyp6,&
             cify6,cisy6,ciwy6,cifyp6,cisyp6,ciwyp6,&    
             pp4y,itime,ditime,nx,ny,nz,nxm,nym,mx,my,mz,adt,bdt,gdt)
!
   USE paramx_m
   USE paramy_m
   USE paramz_m
   USE param1_m
   USE ecoulement_m
   USE delta_m
   USE barreau_m
   USE dericex6_m
   USE interpol6_m
   USE dericey6_m
   USE interpoly6_m
!
   implicit none
!
!******************************************************
  INTEGER, INTENT(IN) :: nx, ny, nz, nxm, nym, mx, my, mz
!********************************************************************
!
  REAL*8, DIMENSION(nx, ny, nz) :: ux, uy, vx, vy, rx, ry
  REAL*8, DIMENSION(nx, ny, nz) :: uxd, uyd, vxd, vyd, rxd, ryd
  REAL*8, DIMENSION(nx, ny, nz) :: u8x, u8y, gx, gy, g8x, g8y
  REAL*8, DIMENSION(nx, ny, nz) :: u8xd, u8yd, gxd, gyd, g8xd, g8yd
  REAL*8, DIMENSION(nx, ny, nz) :: cx, cy, cz, tx, ty, tz
  REAL*8, DIMENSION(nx, ny, nz) :: cxd, cyd, czd, txd, tyd, tzd
  REAL*8, DIMENSION(nx, ny, nz) :: tz1, ty1, ty2, tpx, tpy, tpy1, tpy2
  REAL*8, DIMENSION(nx, ny, nz) :: tz1d, ty1d, ty2d, tpxd, tpyd, tpy1d, &
&  tpy2d
  REAL*8, DIMENSION(nxm, nym, nz) :: wtx, wty
  REAL*8, DIMENSION(nxm, nym, nz) :: wtxd, wtyd
  REAL*8, DIMENSION(nx, nym, nz) :: wty1
  REAL*8, DIMENSION(nx, nym, nz) :: wty1d
  REAL*8, DIMENSION(nxm, ny, nz) :: wtx1
  REAL*8, DIMENSION(nxm, ny, nz) :: wtx1d
  REAL*8, DIMENSION(nxm, nym, nz) :: ppm
  REAL*8, DIMENSION(nxm, nym, nz) :: ppmd
  REAL*8, DIMENSION(mx, my, mz) :: ps, ps1
  REAL*8, DIMENSION(mx, my, mz) :: psd, ps1d
  REAL*8, DIMENSION(mx, my) :: ps2d1
  REAL*8, DIMENSION(mx, my) :: ps2d1d
  REAL*8, DIMENSION(ny, nz) :: bxn, byn
  REAL*8, DIMENSION(ny, nz) :: bxnd, bynd
  REAL*8, DIMENSION(ny, ditime) :: bx1, by1
  REAL*8, DIMENSION(ny, ditime) :: bx1d, by1d
  REAL*8, DIMENSION(nx) :: ffx, fsx, fwx, ffxp, fsxp, fwxp
  REAL*8, DIMENSION(ny) :: ffy, fsy, fwy, ffyp, fsyp, fwyp
  REAL*8, DIMENSION(nz) :: ffz, fsz, fwz, ffzp, fszp, fwzp
  REAL*8, DIMENSION(nx) :: sfx, ssx, swx, sfxp, ssxp, swxp
  REAL*8, DIMENSION(ny) :: sfy, ssy, swy, sfyp, ssyp, swyp
  REAL*8, DIMENSION(nz) :: sfz, ssz, swz, sfzp, sszp, swzp
  REAL*8, DIMENSION(nxm) :: cfx6, csx6, cwx6, cifx6, cisx6, ciwx6
  REAL*8, DIMENSION(nxm) :: cifxp6, cisxp6, ciwxp6, cfxp6, csxp6, cwxp6
  REAL*8, DIMENSION(nym) :: cfy6, csy6, cwy6, cify6, cisy6, ciwy6
  REAL*8, DIMENSION(nym) :: cifyp6, cisyp6, ciwyp6, cfyp6, csyp6, cwyp6
!
!********************* STRET **************************
  REAL*8, DIMENSION(ny) :: pp4y
  REAL*8 :: yl2y
!******************************************************
  REAL*8, INTENT(IN) :: adt, bdt, gdt
!
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: i, j, k, itime, ditime
  REAL*8 :: udxv, vphase, cxv, vphase_sum
  REAL*8 :: vphased, cxvd, vphase_sumd
!----------------------------------------------- 
!
! ******************** urotu *********************
  CALL DERX_D(tz, tzd, uy, uyd, ffxp, fsxp, fwxp, nx, ny, nz, 1)
  CALL DERY_D(cz, czd, ux, uxd, ffyp, fsyp, fwyp, nx, ny, nz, 1)
!
! ******************* visqueux *******************
  CALL DERXX_D(tx, txd, ux, uxd, sfx, ssx, swx, nx, ny, nz, 0)
  CALL DERYY_D(ty, tyd, ux, uxd, sfyp, ssyp, swyp, nx, ny, nz, 1)
  CALL DERY_D(ty1, ty1d, ux, uxd, ffyp, fsyp, fwyp, nx, ny, nz, 1)
  CALL DERXX_D(tpx, tpxd, uy, uyd, sfxp, ssxp, swxp, nx, ny, nz, 1)
  CALL DERYY_D(tpy, tpyd, uy, uyd, sfy, ssy, swy, nx, ny, nz, 0)
  CALL DERY_D(tpy1, tpy1d, uy, uyd, ffy, fsy, fwy, nx, ny, nz, 0)
!
  yl2y = yly*yly
  g8xd = 0.0_8
  g8yd = 0.0_8
  u8xd = 0.0_8
  u8yd = 0.0_8
  tz1d = 0.0_8
  rxd = 0.0_8
  ryd = 0.0_8
  ty2d = 0.0_8
  vxd = 0.0_8
  vyd = 0.0_8
  tpy2d = 0.0_8
  cxd = 0.0_8
  cyd = 0.0_8
!
  DO j=1,ny
    DO i=1,nx
!     ******************** urotu *********************
      tz1d(i, j, 1) = tzd(i, j, 1) - czd(i, j, 1)
      tz1(i, j, 1) = tz(i, j, 1) - cz(i, j, 1)
      cxd(i, j, 1) = -(tz1d(i, j, 1)*uy(i, j, 1)+tz1(i, j, 1)*uyd(i, j, &
&        1))
      cx(i, j, 1) = -(tz1(i, j, 1)*uy(i, j, 1))
      cyd(i, j, 1) = tz1d(i, j, 1)*ux(i, j, 1) + tz1(i, j, 1)*uxd(i, j, &
&        1)
      cy(i, j, 1) = tz1(i, j, 1)*ux(i, j, 1)
!
!     ******************* visqueux *******************
      ty2d(i, j, 1) = yl2y*tyd(i, j, 1) - pp4y(j)*ty1d(i, j, 1)/yl2y
      ty2(i, j, 1) = ty(i, j, 1)*yl2y - pp4y(j)*ty1(i, j, 1)/yl2y
      tpy2d(i, j, 1) = yl2y*tpyd(i, j, 1) - pp4y(j)*tpy1d(i, j, 1)/yl2y
      tpy2(i, j, 1) = tpy(i, j, 1)*yl2y - pp4y(j)*tpy1(i, j, 1)/yl2y
      vxd(i, j, 1) = xnu*(txd(i, j, 1)+ty2d(i, j, 1))
      vx(i, j, 1) = xnu*(tx(i, j, 1)+ty2(i, j, 1))
      vyd(i, j, 1) = xnu*(tpxd(i, j, 1)+tpy2d(i, j, 1))
      vy(i, j, 1) = xnu*(tpx(i, j, 1)+tpy2(i, j, 1))
!
!     ******************** F(u^n) ********************
      rxd(i, j, 1) = vxd(i, j, 1) - cxd(i, j, 1)
      rx(i, j, 1) = vx(i, j, 1) - cx(i, j, 1)
      ryd(i, j, 1) = vyd(i, j, 1) - cyd(i, j, 1)
      ry(i, j, 1) = vy(i, j, 1) - cy(i, j, 1)
!
!     ******************** adams ********************
      u8xd(i, j, 1) = adt*rxd(i, j, 1) + bdt*gxd(i, j, 1) + uxd(i, j, 1)
      u8x(i, j, 1) = adt*rx(i, j, 1) + bdt*gx(i, j, 1) + ux(i, j, 1)
      u8yd(i, j, 1) = adt*ryd(i, j, 1) + bdt*gyd(i, j, 1) + uyd(i, j, 1)
      u8y(i, j, 1) = adt*ry(i, j, 1) + bdt*gy(i, j, 1) + uy(i, j, 1)
      g8xd(i, j, 1) = rxd(i, j, 1)
      g8x(i, j, 1) = rx(i, j, 1)
      g8yd(i, j, 1) = ryd(i, j, 1)
      g8y(i, j, 1) = ry(i, j, 1)
    END DO
  END DO
!
  udxv = 1./dx
!
  vphase_sum = 0.
  vphase_sumd = 0.0_8
  DO j=1,ny
    vphase_sumd = vphase_sumd + uxd(nx, j, 1)
    vphase_sum = vphase_sum + ux(nx, j, 1)
  END DO
  vphased = vphase_sumd/ny
  vphase = vphase_sum/ny
!
  cxvd = gdt*udxv*vphased
  cxv = vphase*gdt*udxv
!
  bxnd = 0.0_8
  bynd = 0.0_8
!
  DO j=1,ny
!   ******************** sortie ********************
    bxnd(j, 1) = uxd(nx, j, 1) - cxvd*(ux(nx, j, 1)-ux(nx-1, j, 1)) - cxv*(uxd(nx, j, 1)-uxd(nx-1, j, 1))
    bxn(j, 1) = ux(nx, j, 1) - cxv*(ux(nx, j, 1)-ux(nx-1, j, 1))
    bynd(j, 1) = uyd(nx, j, 1) - cxvd*(uy(nx, j, 1)-uy(nx-1, j, 1)) - cxv*(uyd(nx, j, 1)-uyd(nx-1, j, 1))
    byn(j, 1) = uy(nx, j, 1) - cxv*(uy(nx, j, 1)-uy(nx-1, j, 1))
!   **************** cond. de borde ****************
    u8xd(nx, j, 1) = bxnd(j, 1)
    u8x(nx, j, 1) = bxn(j, 1)
    u8yd(nx, j, 1) = bynd(j, 1)
    u8y(nx, j, 1) = byn(j, 1)
    u8xd(1, j, 1) = bx1d(j, itime)
    u8x(1, j, 1) = bx1(j, itime)
    u8yd(1, j, 1) = by1d(j, itime)
    u8y(1, j, 1) = by1(j, itime)
  END DO
!
! ******************* divbric16bis ********************
  CALL INTERY6_D(wty1, wty1d, u8x, u8xd, cifyp6, cisyp6, ciwyp6, nx, ny, nym, nz, 1)
  CALL DECX6_D(wtx, wtxd, wty1, wty1d, cfx6, csx6, cwx6, nx, nxm, ny, nym, nz, 0)
  CALL INTER6_D(wtx1, wtx1d, u8y, u8yd, cifxp6, cisxp6, ciwxp6, nx, nxm, ny, nz, 1)
  CALL DECY6_D(wty, wtyd, wtx1, wtx1d, cfy6, csy6, cwy6, nx, nxm, ny, nym, nz, 0)
!    
  ppmd = 0.0_8
  DO j=1,nym
    DO i=1,nxm
      ppmd(i, j, 1) = wtxd(i, j, 1) + wtyd(i, j, 1)
      ppm(i, j, 1) = wtx(i, j, 1) + wty(i, j, 1)
    END DO
  END DO
!
! ******************* temporellebis16STR ********************
! ************** D(nxm,nym,nz) ---> D(mx,my) ****************
  DO k=1,mz
    DO j=1,my
      DO i=1,mx
        psd(i, j, k) = 0.0_8
        ps(i, j, k) = 0.
        ps1d(i, j, k) = 0.0_8
        ps1(i, j, k) = 0.
      END DO
    END DO
  END DO
!
  DO j=1,my
    DO i=1,mx
      ps2d1d(i, j) = 0.0_8
      ps2d1(i, j) = 0.
    END DO
  END DO
  psd = 0.0_8
!
  DO k=1,nz
    DO j=1,nym
      DO i=1,nxm/2
        psd(i, j, k) = ppmd(2*(i-1)+1, j, k)
        ps(i, j, k) = ppm(2*(i-1)+1, j, k)
      END DO
    END DO
  END DO
!
  DO k=1,nz
    DO j=1,nym
      DO i=nxm/2+1,nxm
        psd(i, j, k) = ppmd(2*nxm-2*i+2, j, k)
        ps(i, j, k) = ppm(2*nxm-2*i+2, j, k)
      END DO
    END DO
  END DO
  ps1d = 0.0_8
!
  DO k=1,nz
    DO i=1,nxm
      DO j=1,nym/2
        ps1d(i, j, k) = psd(i, 2*(j-1)+1, k)
        ps1(i, j, k) = ps(i, 2*(j-1)+1, k)
      END DO
    END DO
  END DO
!
  DO k=1,nz
    DO i=1,nxm
      DO j=nym/2+1,nym
        ps1d(i, j, k) = psd(i, 2*nym-2*j+2, k)
        ps1(i, j, k) = ps(i, 2*nym-2*j+2, k)
      END DO
    END DO
  END DO
  ps2d1d = 0.0_8
!
  DO i=1,nxm
    DO j=1,nym
      ps2d1d(i, j) = ps1d(i, j, 1)
      ps2d1(i, j) = ps1(i, j, 1)
    END DO
  END DO
!
  RETURN
END SUBROUTINE FUNCION1_D
