!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion5 in reverse (adjoint) mode:
!   gradient     of useful results: us2d2
!   with respect to varying inputs: us2d1 us2d2
!   RW status of diff variables: us2d1:out us2d2:in-out
!
!  Entrada: us2d2b
!  Salida: us2d1b
! 
!********************************************************************
!
SUBROUTINE FUNCION5_B(us2d1b, us2d2b, mx, my, nx, ny, nxm&
&  , nym)
!
  implicit none
!
  INTEGER :: i, j, mx, my, nx, ny, nxm, nym
!
  REAL*8, DIMENSION(mx, my) :: us2d1, us2d2
  REAL*8, DIMENSION(mx, my) :: us2d1b, us2d2b
  REAL*8, DIMENSION(mx, my) :: ur1, ue1, w1, w11
  REAL*8, DIMENSION(mx, my) :: ur1b, ue1b, w1b, w11b
  REAL*8 :: pi, xx1, xx2, xx3, xx4
  REAL*8 :: xx1b, xx2b, xx3b, xx4b
  REAL*8 :: tmp
  REAL*8 :: tmp0
  REAL*8 :: tmp1
  INTRINSIC COS
  INTRINSIC SIN
  REAL*8 :: tmpb
  REAL*8 :: tmp0b
  INTRINSIC ACOS
  INTRINSIC SQRT
  REAL*8 :: tmp1b
!
  pi = ACOS(-1.)
  DO i=nxm,3,-1
    DO j=my,1,-1
      us2d2b(i, j) = SQRT(2.)*us2d2b(i, j)
    END DO
  END DO
  DO i=mx,1,-1
    tmp1b = us2d2b(i, ny)
    us2d2b(i, ny) = 0.0_8
    us2d2b(i, (ny+1)/2) = us2d2b(i, (ny+1)/2) + tmp1b
  END DO
  DO i=mx,1,-1
    us2d2b(i, ny) = 0.0_8
  END DO
  ue1b = 0.0_8
  ur1b = 0.0_8
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      xx3b = us2d2b(2*i, j)
      xx4b = us2d2b(2*i, j)
      us2d2b(2*i, j) = 0.0_8
      xx1b = us2d2b(2*i-1, j)
      xx2b = us2d2b(2*i-1, j)
      us2d2b(2*i-1, j) = 0.0_8
      ur1b(i, j) = ur1b(i, j) + SIN((j-1)*pi/(2.*nym))*xx4b
      ue1b(i, j) = ue1b(i, j) + COS((j-1)*pi/(2.*nym))*xx4b
      ue1b(i, nym-j+2) = ue1b(i, nym-j+2) + COS((j-1)*pi/(2.*nym))*xx2b &
&        + SIN((j-1)*pi/(2.*nym))*xx3b
      ur1b(i, nym-j+2) = ur1b(i, nym-j+2) + SIN((j-1)*pi/(2.*nym))*xx2b &
&        - SIN((nym-j+1)*pi/(2.*nym))*xx3b
      ur1b(i, j) = ur1b(i, j) + COS((j-1)*pi/(2.*nym))*xx1b
      ue1b(i, j) = ue1b(i, j) - COS((nym-j+1)*pi/(2.*nym))*xx1b
    END DO
  END DO
  DO j=ny,1,-1
    DO i=nxm/2,2,-1
      tmp0b = ue1b(i+nxm/2, j)
      ue1b(i+nxm/2, j) = 0.0_8
      ue1b(nxm/2-i+2, j) = ue1b(nxm/2-i+2, j) - tmp0b
    END DO
  END DO
  DO j=ny,1,-1
    DO i=nxm/2,2,-1
      tmpb = ur1b(i+nxm/2, j)
      ur1b(i+nxm/2, j) = 0.0_8
      ur1b(nxm/2-i+2, j) = ur1b(nxm/2-i+2, j) + tmpb
    END DO
  END DO
  w11b = 0.0_8
  w1b = 0.0_8
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      w1b(i, j) = w1b(i, j) + COS((i-1)*pi/(2.*nxm))*ur1b(i, j) + SIN((i&
&        -1)*pi/(2.*nxm))*ue1b(i, j)
      w11b(i, j) = w11b(i, j) + COS((nxm-i+1)*pi/(2.*nxm))*ur1b(i, j) - &
&        SIN((nxm-i+1)*pi/(2.*nxm))*ue1b(i, j)
      ue1b(i, j) = 0.0_8
      ur1b(i, j) = 0.0_8
    END DO
  END DO
  us2d1b = 0.0_8
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      us2d1b(nxm-i+2, j) = us2d1b(nxm-i+2, j) + w11b(i, j)
      w11b(i, j) = 0.0_8
    END DO
  END DO
  DO j=ny,1,-1
    DO i=nxm/2+1,1,-1
      us2d1b(i, j) = us2d1b(i, j) + w1b(i, j)
      w1b(i, j) = 0.0_8
    END DO
  END DO
!
END SUBROUTINE FUNCION5_B
