!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion4 in forward (tangent) mode:
!   variations   of useful results: us2d
!   with respect to varying inputs: ps2d
!   RW status of diff variables: us2d:out ps2d:in
!
!  Entrada: ps2dd
!  Salida: us2dd
! 
!********************************************************************
!
SUBROUTINE FUNCION4_D(ps2dd, us2dd, a_tot, al_tot, indx_tot&
&  , a2_tot, al1_tot, indx1_tot, d5, m1, m2, nx, nxm, ny, nym, mx, my)
!
  implicit none
!
  INTEGER :: i, j, k, nx, mx, nxm, ny, my, nym, m1, m2
!
  REAL*8, DIMENSION(mx, my) :: ps2d, us2d
  REAL*8, DIMENSION(mx, my) :: ps2dd, us2dd
  REAL*8, DIMENSION(ny/2, m1 + m2 + 1) :: a, a1, a2
  REAL*8, DIMENSION(ny/2, m1) :: al, al1
  REAL*8, DIMENSION(ny/2) :: indx, indx1, e, c, e1, c1
  REAL*8, DIMENSION(ny/2) :: ed, cd, e1d, c1d
  REAL*8, DIMENSION(ny/2, m1 + m2 + 1, nxm) :: a_tot, a2_tot
  REAL*8, DIMENSION(ny/2, m1, nxm) :: al_tot, al1_tot
  REAL*8, DIMENSION(ny/2, nxm) :: indx_tot, indx1_tot
  REAL*8, DIMENSION(nx) :: d5
!
! ******************* temporellebis16STR ********************
! *************** D^d(mx,my) ---> p^d(mx,my) ****************
!
  DO j=1,my
    DO i=1,mx
      us2dd(i, j) = 0.0_8
      us2d(i, j) = 0.
    END DO
  END DO
  us2dd = 0.0_8
  ed = 0.0_8
  c1d = 0.0_8
  e1d = 0.0_8
  cd = 0.0_8
!
  DO i=1,nxm ! Resuelve el sistema B p^ = D^
!
!   Recupera resultados de la descomposicion LU de la matriz de coef. B=A^2
    a = a_tot(:, :, i)
    al = al_tot(:, :, i)
    indx = indx_tot(:, i)
    a2 = a2_tot(:, :, i)
    al1 = al1_tot(:, :, i)
    indx1 = indx1_tot(:, i)
!
    DO j=1,ny/2
      ed(j) = 0.0_8
      e(j) = 0.
      cd(j) = 0.0_8
      c(j) = 0.
      e1d(j) = 0.0_8
      e1(j) = 0.
      c1d(j) = 0.0_8
      c1(j) = 0.
    END DO
!
!   Separamos los a+ib provenientes de D^
    DO j=1,ny/2
      ed(j) = ps2dd(i, 2*j-1)
      e(j) = ps2d(i, 2*j-1)
      cd(j) = ps2dd(i, 2*j)
      c(j) = ps2d(i, 2*j)
    END DO
!     
!   Solves the band diagonal linear equations A·x = e.
!   Given the arrays a, al, and indx as returned from bandec, and given a right-hand-side vector e.
!   The solution vector x se escribe en e1.
    CALL BANBKS1_D(a, ny, my, m1, m2, al, indx, e, ed, e1, e1d)
! 
    CALL BANBKS1_D(a2, ny, my, m1, m2, al1, indx1, c, cd, c1, c1d)
!
!   On reconstruit les a+ib provenientes de p^
    DO j=1,ny-1,2
      us2dd(i, j) = e1d((j+1)/2)
      us2d(i, j) = e1((j+1)/2)
    END DO
    DO j=2,ny,2
      us2dd(i, j) = c1d(j/2)
      us2d(i, j) = c1(j/2)
    END DO
!
    IF (d5(i) .EQ. 0) THEN
      us2dd(i, 1) = 0.0_8
      us2d(i, 1) = 0.
      us2dd(i, ny) = 0.0_8
      us2d(i, ny) = 0.
    END IF
!
  END DO ! Resuelve el sistema B p^ = D^
!
END SUBROUTINE FUNCION4_D
