!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion7 in forward (tangent) mode:
!   variations   of useful results: uxn uyn
!   with respect to varying inputs: us2d3 u8x u8y
!   RW status of diff variables: us2d3:in uxn:out u8x:in u8y:in
!                uyn:out
!
!  Entrada: us2d3d, u8xd, u8yd
!  Salida: uxnd, uynd
!  
!********************************************************************
!
SUBROUTINE FUNCION7_D(us2d3d, u8xd, u8yd, uxnd, &
&  uynd, cfip6, csip6, cwip6, cfip6y, csip6y, cwip6y, cifip6, cisip6&
&  , ciwip6, cifip6y, cisip6y, ciwip6y, nx, nxm, mx, ny, nym, my, nz)
!
   USE paramx_m
   USE paramy_m
!
   implicit none
!
!********************************************************************
  INTEGER :: i, j, k, nx, mx, nxm, ny, my, nym, nz
  REAL*8, DIMENSION(nx, ny, nz) :: uxn, uyn, u8x, u8y, px, py
  REAL*8, DIMENSION(nx, ny, nz) :: uxnd, uynd, u8xd, u8yd, pxd, pyd
  REAL*8, DIMENSION(nxm, nym, nz) :: ppm
  REAL*8, DIMENSION(nxm, nym, nz) :: ppmd
  REAL*8, DIMENSION(nxm, ny, nz) :: wk1
  REAL*8, DIMENSION(nxm, ny, nz) :: wk1d
  REAL*8, DIMENSION(nx, nym, nz) :: wk2
  REAL*8, DIMENSION(nx, nym, nz) :: wk2d
  REAL*8, DIMENSION(mx, my) :: us2d3, ux2d, pp2d
  REAL*8, DIMENSION(mx, my) :: us2d3d, ux2dd, pp2dd
  REAL*8, DIMENSION(nx) :: cfip6, csip6, cwip6
  REAL*8, DIMENSION(nx) :: cifip6, cisip6, ciwip6
  REAL*8, DIMENSION(ny) :: cfip6y, csip6y, cwip6y
  REAL*8, DIMENSION(ny) :: cifip6y, cisip6y, ciwip6y
!
! ******************* temporellebis16STR ********************
! ************** p(mx,my) ---> p(nxm,nym,nz) ****************
  pp2dd = 0.0_8
  DO j=1,ny
    DO i=1,nxm/2
      pp2dd(2*i-1, j) = us2d3d(i, j)
      pp2d(2*i-1, j) = us2d3(i, j)
    END DO
  END DO
!
  DO j=1,ny
    DO i=1,nxm/2
      pp2dd(2*i, j) = us2d3d(nxm-i+1, j)
      pp2d(2*i, j) = us2d3(nxm-i+1, j)
    END DO
  END DO
  ux2dd = 0.0_8
!      
  DO j=1,nym/2
    DO i=1,nxm
      ux2dd(i, 2*j-1) = pp2dd(i, j)
      ux2d(i, 2*j-1) = pp2d(i, j)
    END DO
  END DO
!     
  DO j=1,nym/2
    DO i=1,nxm
      ux2dd(i, 2*j) = pp2dd(i, nym-j+1)
      ux2d(i, 2*j) = pp2d(i, nym-j+1)
    END DO
  END DO
  ppmd = 0.0_8
!
  DO k=1,nz
    DO i=1,nxm
      DO j=1,nym
        ppmd(i, j, k) = ux2dd(i, j)
        ppm(i, j, k) = ux2d(i, j)
      END DO
    END DO
  END DO
!
! ********************* gradpbis16 **********************
  CALL INTERIY6_D(wk1, wk1d, ppm, ppmd, cifip6y, cisip6y, ciwip6y, nxm, &
&            nym, ny, nz, 1)
  CALL DECI6_D(px, pxd, wk1, wk1d, cfip6, csip6, cwip6, nxm, nx, ny, nz&
&         , 1)
  CALL INTERI6_D(wk2, wk2d, ppm, ppmd, cifip6, cisip6, ciwip6, nxm, nx, &
&           nym, nz, 1)
  CALL DECIY6_D(py, pyd, wk2, wk2d, cfip6y, csip6y, cwip6y, nx, nym, ny&
&          , nz, 1)
!
! ********************** corgp ***********************
  uxnd = 0.0_8
  uynd = 0.0_8
  DO j=1,ny
    DO i=1,nx
      uxnd(i, j, 1) = u8xd(i, j, 1) - pxd(i, j, 1)
      uxn(i, j, 1) = -px(i, j, 1) + u8x(i, j, 1)
      uynd(i, j, 1) = u8yd(i, j, 1) - pyd(i, j, 1)
      uyn(i, j, 1) = -py(i, j, 1) + u8y(i, j, 1)
    END DO
  END DO
!
  RETURN
END SUBROUTINE FUNCION7_D
