!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion7 in reverse (adjoint) mode:
!   gradient     of useful results: uxn uyn
!   with respect to varying inputs: us2d3 uxn u8x u8y uyn
!   RW status of diff variables: us2d3:out uxn:in-out u8x:out u8y:out
!                uyn:in-out
!
!  Entrada: uxnb, uynb
!  Salida: us2d3b, u8xb, u8yb
!  
!********************************************************************
!
SUBROUTINE FUNCION7_B(us2d3b, u8xb, u8yb, uxnb, &
&  uynb, cfip6, csip6, cwip6, cfip6y, csip6y, cwip6y, cifip6, cisip6&
&  , ciwip6, cifip6y, cisip6y, ciwip6y, nx, nxm, mx, ny, nym, my, nz)
!
   USE paramx_m
   USE paramy_m
!
   implicit none
!
!********************************************************************
  INTEGER :: i, j, k, nx, mx, nxm, ny, my, nym, nz
  REAL*8, DIMENSION(nx, ny, nz) :: uxn, uyn, u8x, u8y, px, py
  REAL*8, DIMENSION(nx, ny, nz) :: uxnb, uynb, u8xb, u8yb, pxb, pyb
  REAL*8, DIMENSION(nxm, nym, nz) :: ppm
  REAL*8, DIMENSION(nxm, nym, nz) :: ppmb
  REAL*8, DIMENSION(nxm, ny, nz) :: wk1
  REAL*8, DIMENSION(nxm, ny, nz) :: wk1b
  REAL*8, DIMENSION(nx, nym, nz) :: wk2
  REAL*8, DIMENSION(nx, nym, nz) :: wk2b
  REAL*8, DIMENSION(mx, my) :: us2d3, ux2d, pp2d
  REAL*8, DIMENSION(mx, my) :: us2d3b, ux2db, pp2db
  REAL*8, DIMENSION(nx) :: cfip6, csip6, cwip6
  REAL*8, DIMENSION(nx) :: cifip6, cisip6, ciwip6
  REAL*8, DIMENSION(ny) :: cfip6y, csip6y, cwip6y
  REAL*8, DIMENSION(ny) :: cifip6y, cisip6y, ciwip6y
!
  u8xb = 0.0_8
  u8yb = 0.0_8
  pxb = 0.0_8
  pyb = 0.0_8
  DO j=ny,1,-1
    DO i=nx,1,-1
      u8yb(i, j, 1) = u8yb(i, j, 1) + uynb(i, j, 1)
      pyb(i, j, 1) = pyb(i, j, 1) - uynb(i, j, 1)
      uynb(i, j, 1) = 0.0_8
      u8xb(i, j, 1) = u8xb(i, j, 1) + uxnb(i, j, 1)
      pxb(i, j, 1) = pxb(i, j, 1) - uxnb(i, j, 1)
      uxnb(i, j, 1) = 0.0_8
    END DO
  END DO
!
  CALL DECIY6_B(py, pyb, wk2, wk2b, cfip6y, csip6y, cwip6y, nx, nym, ny&
&          , nz, 1)
  CALL INTERI6_B(wk2, wk2b, ppm, ppmb, cifip6, cisip6, ciwip6, nxm, nx, &
&           nym, nz, 1)
  CALL DECI6_B(px, pxb, wk1, wk1b, cfip6, csip6, cwip6, nxm, nx, ny, nz&
&         , 1)
  CALL INTERIY6_B(wk1, wk1b, ppm, ppmb, cifip6y, cisip6y, ciwip6y, nxm, &
&            nym, ny, nz, 1)
!
  ux2db = 0.0_8
  DO k=nz,1,-1
    DO i=nxm,1,-1
      DO j=nym,1,-1
        ux2db(i, j) = ux2db(i, j) + ppmb(i, j, k)
        ppmb(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
!
  pp2db = 0.0_8
  DO j=nym/2,1,-1
    DO i=nxm,1,-1
      pp2db(i, nym-j+1) = pp2db(i, nym-j+1) + ux2db(i, 2*j)
      ux2db(i, 2*j) = 0.0_8
    END DO
  END DO
!
  DO j=nym/2,1,-1
    DO i=nxm,1,-1
      pp2db(i, j) = pp2db(i, j) + ux2db(i, 2*j-1)
      ux2db(i, 2*j-1) = 0.0_8
    END DO
  END DO
!
  us2d3b = 0.0_8
  DO j=ny,1,-1
    DO i=nxm/2,1,-1
      us2d3b(nxm-i+1, j) = us2d3b(nxm-i+1, j) + pp2db(2*i, j)
      pp2db(2*i, j) = 0.0_8
    END DO
  END DO
!
  DO j=ny,1,-1
    DO i=nxm/2,1,-1
      us2d3b(i, j) = us2d3b(i, j) + pp2db(2*i-1, j)
      pp2db(2*i-1, j) = 0.0_8
    END DO
  END DO
!
END SUBROUTINE FUNCION7_B
