!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of funcion6 in reverse (adjoint) mode:
!   gradient     of useful results: g8x g8y ps2d1 u8x u8y
!   with respect to varying inputs: gx gy g8x g8y ux uy ps2d1 u8x
!                u8y bx1 by1
!   RW status of diff variables: gx:out gy:out g8x:in-out g8y:in-out
!                ux:out uy:out ps2d1:in-out u8x:in-out u8y:in-out
!                bx1:out by1:out
!
!  Entrada: ux, uy, gx, gy, bx1, by1, u8xb, u8yb, g8xb, g8yb, ps2d1b
!  Salida: uxb, uyb, gxb, gyb, bx1b, by1b
! 
!********************************************************************
!
SUBROUTINE FUNCION1_B(ux,uxb,uy,uyb,gx,gxb,gy,gyb,bx1,bx1b,by1,by1b,&
             u8x,u8xb,u8y,u8yb,g8x,g8xb,g8y,g8yb,ps2d1,ps2d1b,&
             ffx,fsx,fwx,ffy,fsy,fwy,&
             ffxp,fsxp,fwxp,&
             ffyp,fsyp,fwyp,&
             sfx,ssx,swx,sfy,ssy,swy,&
             sfxp,ssxp,swxp,&
             sfyp,ssyp,swyp,&
             cfx6,csx6,cwx6,&
             cfxp6,csxp6,cwxp6,&
             cifx6,cisx6,ciwx6,cifxp6,cisxp6,ciwxp6,&
             cfy6,csy6,cwy6,cfyp6,csyp6,cwyp6,&
             cify6,cisy6,ciwy6,cifyp6,cisyp6,ciwyp6,&    
             pp4y,itime,ditime,nx,ny,nz,nxm,nym,mx,my,mz,adt,bdt,gdt)
!
   USE paramx_m
   USE paramy_m
   USE paramz_m
   USE param1_m
   USE ecoulement_m
   USE delta_m
   USE barreau_m
   USE dericex6_m
   USE interpol6_m
   USE dericey6_m
   USE interpoly6_m
!
   implicit none
!
!******************************************************
  INTEGER, INTENT(IN) :: nx, ny, nz, nxm, nym, mx, my, mz
!********************************************************************
!
  REAL*8, DIMENSION(nx, ny, nz) :: ux, uy, vx, vy, rx, ry
  REAL*8, DIMENSION(nx, ny, nz) :: uxb, uyb, vxb, vyb, rxb, ryb
  REAL*8, DIMENSION(nx, ny, nz) :: u8x, u8y, gx, gy, g8x, g8y
  REAL*8, DIMENSION(nx, ny, nz) :: u8xb, u8yb, gxb, gyb, g8xb, g8yb
  REAL*8, DIMENSION(nx, ny, nz) :: cx, cy, cz, tx, ty, tz
  REAL*8, DIMENSION(nx, ny, nz) :: cxb, cyb, czb, txb, tyb, tzb
  REAL*8, DIMENSION(nx, ny, nz) :: tz1, ty1, ty2, tpx, tpy, tpy1, tpy2
  REAL*8, DIMENSION(nx, ny, nz) :: tz1b, ty1b, ty2b, tpxb, tpyb, tpy1b, &
&  tpy2b
  REAL*8, DIMENSION(nxm, nym, nz) :: wtx, wty
  REAL*8, DIMENSION(nxm, nym, nz) :: wtxb, wtyb
  REAL*8, DIMENSION(nx, nym, nz) :: wty1
  REAL*8, DIMENSION(nx, nym, nz) :: wty1b
  REAL*8, DIMENSION(nxm, ny, nz) :: wtx1
  REAL*8, DIMENSION(nxm, ny, nz) :: wtx1b
  REAL*8, DIMENSION(nxm, nym, nz) :: ppm
  REAL*8, DIMENSION(nxm, nym, nz) :: ppmb
  REAL*8, DIMENSION(mx, my, mz) :: ps, ps1
  REAL*8, DIMENSION(mx, my, mz) :: psb, ps1b
  REAL*8, DIMENSION(mx, my) :: ps2d1
  REAL*8, DIMENSION(mx, my) :: ps2d1b
  REAL*8, DIMENSION(ny, nz) :: bxn, byn
  REAL*8, DIMENSION(ny, nz) :: bxnb, bynb
  REAL*8, DIMENSION(ny, ditime) :: bx1, by1
  REAL*8, DIMENSION(ny, ditime) :: bx1b, by1b
  REAL*8, DIMENSION(nx) :: ffx, fsx, fwx, ffxp, fsxp, fwxp
  REAL*8, DIMENSION(ny) :: ffy, fsy, fwy, ffyp, fsyp, fwyp
  REAL*8, DIMENSION(nz) :: ffz, fsz, fwz, ffzp, fszp, fwzp
  REAL*8, DIMENSION(nx) :: sfx, ssx, swx, sfxp, ssxp, swxp
  REAL*8, DIMENSION(ny) :: sfy, ssy, swy, sfyp, ssyp, swyp
  REAL*8, DIMENSION(nz) :: sfz, ssz, swz, sfzp, sszp, swzp
  REAL*8, DIMENSION(nxm) :: cfx6, csx6, cwx6, cifx6, cisx6, ciwx6
  REAL*8, DIMENSION(nxm) :: cifxp6, cisxp6, ciwxp6, cfxp6, csxp6, cwxp6
  REAL*8, DIMENSION(nym) :: cfy6, csy6, cwy6, cify6, cisy6, ciwy6
  REAL*8, DIMENSION(nym) :: cifyp6, cisyp6, ciwyp6, cfyp6, csyp6, cwyp6
!
!********************* STRET **************************
  REAL*8, DIMENSION(ny) :: pp4y
  REAL*8 :: yl2y
!******************************************************
  REAL*8, INTENT(IN) :: adt, bdt, gdt
!
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: i, j, k, itime, ditime
  REAL*8 :: udxv, vphase, cxv, vphase_sum
  REAL*8 :: vphaseb, cxvb, vphase_sumb
!----------------------------------------------- 
!
  ps1b = 0.0_8
  DO i=nxm,1,-1
    DO j=nym,1,-1
      ps1b(i, j, 1) = ps1b(i, j, 1) + ps2d1b(i, j)
      ps2d1b(i, j) = 0.0_8
    END DO
  END DO
  psb = 0.0_8
  DO k=nz,1,-1
    DO i=nxm,1,-1
      DO j=nym,nym/2+1,-1
        psb(i, 2*nym-2*j+2, k) = psb(i, 2*nym-2*j+2, k) + ps1b(i, j, k)
        ps1b(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  DO k=nz,1,-1
    DO i=nxm,1,-1
      DO j=nym/2,1,-1
        psb(i, 2*(j-1)+1, k) = psb(i, 2*(j-1)+1, k) + ps1b(i, j, k)
        ps1b(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  ppmb = 0.0_8
  DO k=nz,1,-1
    DO j=nym,1,-1
      DO i=nxm,nxm/2+1,-1
        ppmb(2*nxm-2*i+2, j, k) = ppmb(2*nxm-2*i+2, j, k) + psb(i, j, k)
        psb(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  DO k=nz,1,-1
    DO j=nym,1,-1
      DO i=nxm/2,1,-1
        ppmb(2*(i-1)+1, j, k) = ppmb(2*(i-1)+1, j, k) + psb(i, j, k)
        psb(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  DO j=my,1,-1
    DO i=mx,1,-1
      ps2d1b(i, j) = 0.0_8
    END DO
  END DO
!
  wtxb = 0.0_8
  wtyb = 0.0_8
  DO j=nym,1,-1
    DO i=nxm,1,-1
      wtxb(i, j, 1) = wtxb(i, j, 1) + ppmb(i, j, 1)
      wtyb(i, j, 1) = wtyb(i, j, 1) + ppmb(i, j, 1)
      ppmb(i, j, 1) = 0.0_8
    END DO
  END DO
!
  CALL DECY6_B(wty, wtyb, wtx1, wtx1b, cfy6, csy6, cwy6, nx, nxm, ny, &
&         nym, nz, 0)
  CALL INTER6_B(wtx1, wtx1b, u8y, u8yb, cifxp6, cisxp6, ciwxp6, nx, nxm&
&          , ny, nz, 1)
  CALL DECX6_B(wtx, wtxb, wty1, wty1b, cfx6, csx6, cwx6, nx, nxm, ny, &
&         nym, nz, 0)
  CALL INTERY6_B(wty1, wty1b, u8x, u8xb, cifyp6, cisyp6, ciwyp6, nx, ny&
&           , nym, nz, 1)
!
  udxv = 1./dx
!
  vphase_sum = 0.
  DO j=1,ny
    vphase_sum = vphase_sum + ux(nx, j, 1)
  END DO
  vphase = vphase_sum/ny
!
  cxv = vphase*gdt*udxv
  cxvb = 0.0_8
!
  uxb = 0.0_8
  uyb = 0.0_8
  bx1b(:,itime) = 0.0_8
  by1b(:,itime) = 0.0_8
  bxnb = 0.0_8
  bynb = 0.0_8
  DO j=ny,1,-1
    by1b(j, itime) = by1b(j, itime) + u8yb(1, j, 1)
    u8yb(1, j, 1) = 0.0_8
    bx1b(j, itime) = bx1b(j, itime) + u8xb(1, j, 1)
    u8xb(1, j, 1) = 0.0_8
    bynb(j, 1) = bynb(j, 1) + u8yb(nx, j, 1)
    u8yb(nx, j, 1) = 0.0_8
    bxnb(j, 1) = bxnb(j, 1) + u8xb(nx, j, 1)
    u8xb(nx, j, 1) = 0.0_8
    cxvb = cxvb - (ux(nx, j, 1)-ux(nx-1, j, 1))*bxnb(j, 1) - (uy(nx, j, 1)-uy(nx-1, j, 1))*bynb(j, 1)
    uyb(nx, j, 1) = uyb(nx, j, 1) + (1.0-cxv)*bynb(j, 1)
    uyb(nx-1, j, 1) = uyb(nx-1, j, 1) + cxv*bynb(j, 1)
    bynb(j, 1) = 0.0_8
    uxb(nx, j, 1) = uxb(nx, j, 1) + (1.0-cxv)*bxnb(j, 1)
    uxb(nx-1, j, 1) = uxb(nx-1, j, 1) + cxv*bxnb(j, 1)
    bxnb(j, 1) = 0.0_8
  END DO
!
  vphaseb = gdt*udxv*cxvb
  vphase_sumb = vphaseb/ny
  DO j=ny,1,-1
    uxb(nx, j, 1) = uxb(nx, j, 1) + vphase_sumb
  END DO
!
  CALL DERX(tz, uy, ffxp, fsxp, fwxp, nx, ny, nz, 1)
  CALL DERY(cz, ux, ffyp, fsyp, fwyp, nx, ny, nz, 1)
!
  yl2y = yly*yly
!
  DO j=1,ny
    DO i=1,nx
      tz1(i, j, 1) = tz(i, j, 1) - cz(i, j, 1)
    END DO
  END DO
!
  gxb = 0.0_8
  gyb = 0.0_8
  tz1b = 0.0_8
  txb = 0.0_8
  tyb = 0.0_8
  tzb = 0.0_8
  rxb = 0.0_8
  ryb = 0.0_8
  tpxb = 0.0_8
  tpyb = 0.0_8
  ty1b = 0.0_8
  ty2b = 0.0_8
  vxb = 0.0_8
  vyb = 0.0_8
  tpy1b = 0.0_8
  tpy2b = 0.0_8
  cxb = 0.0_8
  cyb = 0.0_8
  czb = 0.0_8
  DO j=ny,1,-1
    DO i=nx,1,-1
      ryb(i, j, 1) = ryb(i, j, 1) + adt*u8yb(i, j, 1) + g8yb(i, j, 1)
      g8yb(i, j, 1) = 0.0_8
      rxb(i, j, 1) = rxb(i, j, 1) + adt*u8xb(i, j, 1) + g8xb(i, j, 1)
      g8xb(i, j, 1) = 0.0_8
      gyb(i, j, 1) = gyb(i, j, 1) + bdt*u8yb(i, j, 1)
      cxb(i, j, 1) = cxb(i, j, 1) - rxb(i, j, 1)
      uyb(i, j, 1) = uyb(i, j, 1) + u8yb(i, j, 1) - tz1(i, j, 1)*cxb(i, &
&        j, 1)
      u8yb(i, j, 1) = 0.0_8
      gxb(i, j, 1) = gxb(i, j, 1) + bdt*u8xb(i, j, 1)
      cyb(i, j, 1) = cyb(i, j, 1) - ryb(i, j, 1)
      uxb(i, j, 1) = uxb(i, j, 1) + tz1(i, j, 1)*cyb(i, j, 1) + u8xb(i, &
&        j, 1)
      u8xb(i, j, 1) = 0.0_8
      vyb(i, j, 1) = vyb(i, j, 1) + ryb(i, j, 1)
      ryb(i, j, 1) = 0.0_8
      vxb(i, j, 1) = vxb(i, j, 1) + rxb(i, j, 1)
      rxb(i, j, 1) = 0.0_8
      tpxb(i, j, 1) = tpxb(i, j, 1) + xnu*vyb(i, j, 1)
      tpy2b(i, j, 1) = tpy2b(i, j, 1) + xnu*vyb(i, j, 1)
      vyb(i, j, 1) = 0.0_8
      txb(i, j, 1) = txb(i, j, 1) + xnu*vxb(i, j, 1)
      ty2b(i, j, 1) = ty2b(i, j, 1) + xnu*vxb(i, j, 1)
      vxb(i, j, 1) = 0.0_8
      tpyb(i, j, 1) = tpyb(i, j, 1) + yl2y*tpy2b(i, j, 1)
      tpy1b(i, j, 1) = tpy1b(i, j, 1) - pp4y(j)*tpy2b(i, j, 1)/yl2y
      tpy2b(i, j, 1) = 0.0_8
      tyb(i, j, 1) = tyb(i, j, 1) + yl2y*ty2b(i, j, 1)
      ty1b(i, j, 1) = ty1b(i, j, 1) - pp4y(j)*ty2b(i, j, 1)/yl2y
      ty2b(i, j, 1) = 0.0_8
      tz1b(i, j, 1) = tz1b(i, j, 1) + ux(i, j, 1)*cyb(i, j, 1) - uy(i, j&
&        , 1)*cxb(i, j, 1)
      cyb(i, j, 1) = 0.0_8
      cxb(i, j, 1) = 0.0_8
      tzb(i, j, 1) = tzb(i, j, 1) + tz1b(i, j, 1)
      czb(i, j, 1) = czb(i, j, 1) - tz1b(i, j, 1)
      tz1b(i, j, 1) = 0.0_8
    END DO
  END DO
!
  CALL DERY_B(tpy1, tpy1b, uy, uyb, ffy, fsy, fwy, nx, ny, nz, 0)
  CALL DERYY_B(tpy, tpyb, uy, uyb, sfy, ssy, swy, nx, ny, nz, 0)
  CALL DERXX_B(tpx, tpxb, uy, uyb, sfxp, ssxp, swxp, nx, ny, nz, 1)
  CALL DERY_B(ty1, ty1b, ux, uxb, ffyp, fsyp, fwyp, nx, ny, nz, 1)
  CALL DERYY_B(ty, tyb, ux, uxb, sfyp, ssyp, swyp, nx, ny, nz, 1)
  CALL DERXX_B(tx, txb, ux, uxb, sfx, ssx, swx, nx, ny, nz, 0)
  CALL DERY_B(cz, czb, ux, uxb, ffyp, fsyp, fwyp, nx, ny, nz, 1)
  CALL DERX_B(tz, tzb, uy, uyb, ffxp, fsxp, fwxp, nx, ny, nz, 1)
!
END SUBROUTINE FUNCION1_B
