!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of interiy16 in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE INTERIY16_D(ty, tyd, uy, uyd, cifi6y, cisi6y, ciwi6y, nx, nym&
&  , ny, nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE interpoly6_m 
  USE paramy_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, nxm, ny, nym, nz, npaire
  REAL*8, DIMENSION(nx, nz, ny) :: ty
  REAL*8, DIMENSION(nx, nz, ny) :: tyd
  REAL*8, DIMENSION(nx, nz, nym) :: uy
  REAL*8, DIMENSION(nx, nz, nym) :: uyd
  REAL*8, DIMENSION(ny) :: cifi6y, cisi6y, ciwi6y
!
  INTEGER :: i, j, k
!
  IF (npaire .EQ. 1) THEN
    tyd = 0.0_8
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, 1) = aiciy6*2*uyd(i, k, 1) + biciy6*2*uyd(i, k, 2)
        ty(i, k, 1) = aiciy6*(uy(i, k, 1)+uy(i, k, 1)) + biciy6*(uy(i, k&
&          , 2)+uy(i, k, 2))
        tyd(i, k, 2) = aiciy6*(uyd(i, k, 2)+uyd(i, k, 1)) + biciy6*(uyd(&
&          i, k, 3)+uyd(i, k, 1))
        ty(i, k, 2) = aiciy6*(uy(i, k, 2)+uy(i, k, 1)) + biciy6*(uy(i, k&
&          , 3)+uy(i, k, 1))
      END DO
    END DO
    DO j=3,ny-2
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = aiciy6*(uyd(i, k, j)+uyd(i, k, j-1)) + biciy6*(&
&            uyd(i, k, j+1)+uyd(i, k, j-2))
          ty(i, k, j) = aiciy6*(uy(i, k, j)+uy(i, k, j-1)) + biciy6*(uy(&
&            i, k, j+1)+uy(i, k, j-2))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, ny-1) = aiciy6*(uyd(i, k, ny-1)+uyd(i, k, ny-2)) + &
&          biciy6*(uyd(i, k, ny-1)+uyd(i, k, ny-3))
        ty(i, k, ny-1) = aiciy6*(uy(i, k, ny-1)+uy(i, k, ny-2)) + biciy6&
&          *(uy(i, k, ny-1)+uy(i, k, ny-3))
        tyd(i, k, ny) = aiciy6*2*uyd(i, k, ny-1) + biciy6*2*uyd(i, k, ny&
&          -2)
        ty(i, k, ny) = aiciy6*(uy(i, k, ny-1)+uy(i, k, ny-1)) + biciy6*(&
&          uy(i, k, ny-2)+uy(i, k, ny-2))
      END DO
    END DO
    DO j=2,ny
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = tyd(i, k, j) - cisi6y(j)*tyd(i, k, j-1)
          ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*cisi6y(j)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, ny) = ciwi6y(ny)*tyd(i, k, ny)
        ty(i, k, ny) = ty(i, k, ny)*ciwi6y(ny)
      END DO
    END DO
    DO j=ny-1,1,-1
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = ciwi6y(j)*(tyd(i, k, j)-cifi6y(j)*tyd(i, k, j+1&
&            ))
          ty(i, k, j) = (ty(i, k, j)-cifi6y(j)*ty(i, k, j+1))*ciwi6y(j)
        END DO
      END DO
    END DO
  ELSE
    tyd = 0.0_8
  END IF
!
  RETURN
END SUBROUTINE INTERIY16_D
