!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of intery6 in reverse (adjoint) mode:
!   gradient     of useful results: ty uy
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE INTERY6_B(ty, tyb, uy, uyb, cify6, cisy6, ciwy6, nx, ny, nym&
&  , nz, npaire)
!
  USE paramy_m
  implicit none
!
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, ny, nym, nz, npaire
  REAL*8 :: ty(nx, nym, nz)
  REAL*8 :: tyb(nx, nym, nz)
  REAL*8, INTENT(IN) :: uy(nx, ny, nz)
  REAL*8 :: uyb(nx, ny, nz)
  REAL*8 :: ry(nx, nz, nym)
  REAL*8 :: ryb(nx, nz, nym)
  REAL*8 :: di(nx, nz, ny)
  REAL*8 :: dib(nx, nz, ny)
  REAL*8 :: cify6(nym)
  REAL*8 :: cisy6(nym)
  REAL*8 :: ciwy6(nym)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
  ryb = 0.0_8
!
  DO k=nz,1,-1
    DO j=nym,1,-1
      DO i=nx,1,-1
        ryb(i, k, j) = ryb(i, k, j) + tyb(i, j, k)
        tyb(i, j, k) = 0.0_8
      END DO
    END DO
  END DO
  CALL INTERY16_B(ry, ryb, di, dib, cify6, cisy6, ciwy6, nx, ny, nym, nz&
&            , npaire)
  DO k=nz,1,-1
    DO j=ny,1,-1
      DO i=nx,1,-1
        uyb(i, j, k) = uyb(i, j, k) + dib(i, k, j)
        dib(i, k, j) = 0.0_8
      END DO
    END DO
  END DO
END SUBROUTINE INTERY6_B
