!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of intery16 in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE INTERY16_D(ty, tyd, uy, uyd, cify6, cisy6, ciwy6, nx, ny, nym&
&  , nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE interpoly6_m 
  USE paramy_m 
  USE derivey_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx, ny, nym, nz, npaire
  REAL*8, INTENT(INOUT) :: ty(nx, nz, nym)
  REAL*8, INTENT(INOUT) :: tyd(nx, nz, nym)
  REAL*8, INTENT(IN) :: uy(nx, nz, ny)
  REAL*8, INTENT(IN) :: uyd(nx, nz, ny)
  REAL*8, INTENT(IN) :: cify6(nym)
  REAL*8, INTENT(IN) :: cisy6(nym)
  REAL*8, INTENT(IN) :: ciwy6(nym)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, i, j
!-----------------------------------------------
!
!********************************************************************
!
  IF (npaire .EQ. 1) THEN
    tyd = 0.0_8
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, 1) = aiciy6*(uyd(i, k, 2)+uyd(i, k, 1)) + biciy6*(uyd(&
&          i, k, 3)+uyd(i, k, 2))
        ty(i, k, 1) = aiciy6*(uy(i, k, 2)+uy(i, k, 1)) + biciy6*(uy(i, k&
&          , 3)+uy(i, k, 2))
        tyd(i, k, 2) = aiciy6*(uyd(i, k, 3)+uyd(i, k, 2)) + biciy6*(uyd(&
&          i, k, 4)+uyd(i, k, 1))
        ty(i, k, 2) = aiciy6*(uy(i, k, 3)+uy(i, k, 2)) + biciy6*(uy(i, k&
&          , 4)+uy(i, k, 1))
      END DO
    END DO
    DO j=3,nym-2
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = aiciy6*(uyd(i, k, j+1)+uyd(i, k, j)) + biciy6*(&
&            uyd(i, k, j+2)+uyd(i, k, j-1))
          ty(i, k, j) = aiciy6*(uy(i, k, j+1)+uy(i, k, j)) + biciy6*(uy(&
&            i, k, j+2)+uy(i, k, j-1))
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, nym-1) = aiciy6*(uyd(i, k, nym)+uyd(i, k, nym-1)) + &
&          biciy6*(uyd(i, k, ny)+uyd(i, k, nym-2))
        ty(i, k, nym-1) = aiciy6*(uy(i, k, nym)+uy(i, k, nym-1)) + &
&          biciy6*(uy(i, k, ny)+uy(i, k, nym-2))
        tyd(i, k, nym) = aiciy6*(uyd(i, k, ny)+uyd(i, k, nym)) + biciy6*&
&          (uyd(i, k, nym)+uyd(i, k, nym-1))
        ty(i, k, nym) = aiciy6*(uy(i, k, ny)+uy(i, k, nym)) + biciy6*(uy&
&          (i, k, nym)+uy(i, k, nym-1))
      END DO
    END DO
    DO j=2,nym
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = tyd(i, k, j) - cisy6(j)*tyd(i, k, j-1)
          ty(i, k, j) = ty(i, k, j) - ty(i, k, j-1)*cisy6(j)
        END DO
      END DO
    END DO
    DO k=1,nz
      DO i=1,nx
        tyd(i, k, nym) = ciwy6(nym)*tyd(i, k, nym)
        ty(i, k, nym) = ty(i, k, nym)*ciwy6(nym)
      END DO
    END DO
    DO j=nym-1,1,-1
      DO k=1,nz
        DO i=1,nx
          tyd(i, k, j) = ciwy6(j)*(tyd(i, k, j)-cify6(j)*tyd(i, k, j+1))
          ty(i, k, j) = (ty(i, k, j)-cify6(j)*ty(i, k, j+1))*ciwy6(j)
        END DO
      END DO
    END DO
  ELSE
    tyd = 0.0_8
  END IF
! 
  RETURN
END SUBROUTINE INTERY16_D
