!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of intery6 in forward (tangent) mode:
!   variations   of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE INTERY6_D(ty, tyd, uy, uyd, cify6, cisy6, ciwy6, nx, ny, nym&
&  , nz, npaire)
!
  USE paramy_m
  implicit none
!
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER :: nx, ny, nym, nz, npaire
  REAL*8 :: ty(nx, nym, nz)
  REAL*8 :: tyd(nx, nym, nz)
  REAL*8, INTENT(IN) :: uy(nx, ny, nz)
  REAL*8, INTENT(IN) :: uyd(nx, ny, nz)
  REAL*8 :: ry(nx, nz, nym)
  REAL*8 :: ryd(nx, nz, nym)
  REAL*8 :: di(nx, nz, ny)
  REAL*8 :: did(nx, nz, ny)
  REAL*8 :: cify6(nym)
  REAL*8 :: cisy6(nym)
  REAL*8 :: ciwy6(nym)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
  did = 0.0_8
!-----------------------------------------------
!
!********************************************************************
!
  DO k=1,nz
    DO j=1,ny
      DO i=1,nx
        did(i, k, j) = uyd(i, j, k)
        di(i, k, j) = uy(i, j, k)
      END DO
    END DO
  END DO
!
  CALL INTERY16_D(ry, ryd, di, did, cify6, cisy6, ciwy6, nx, ny, nym, nz&
&            , npaire)
  tyd = 0.0_8
!
  DO k=1,nz
    DO j=1,nym
      DO i=1,nx
        tyd(i, j, k) = ryd(i, k, j)
        ty(i, j, k) = ry(i, k, j)
      END DO
    END DO
  END DO
!
  RETURN
END SUBROUTINE INTERY6_D
