!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of inter6 in reverse (adjoint) mode:
!   gradient     of useful results: tx ux
!   with respect to varying inputs: ux
!
!********************************************************************
!
SUBROUTINE INTER6_B(tx, txb, ux, uxb, cifx6, cisx6, ciwx6, nx, nxm, ny, &
&  nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE paramx_m 
  USE interpol6_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx, nxm, ny, nz, npaire
  REAL*8, INTENT(INOUT) :: tx(nxm, ny, nz)
  REAL*8 :: txb(nxm, ny, nz)
  REAL*8, INTENT(IN) :: ux(nx, ny, nz)
  REAL*8 :: uxb(nx, ny, nz)
  REAL*8, INTENT(IN) :: cifx6(nxm)
  REAL*8, INTENT(IN) :: cisx6(nxm)
  REAL*8, INTENT(IN) :: ciwx6(nxm)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, j, i
!-----------------------------------------------
!
!********************************************************************
!   
  IF (npaire .EQ. 1) THEN
    DO i=1,nxm-1,1
      DO k=nz,1,-1
        DO j=ny,1,-1
          txb(i+1, j, k) = txb(i+1, j, k) - ciwx6(i)*cifx6(i)*txb(i, j, &
&            k)
          txb(i, j, k) = ciwx6(i)*txb(i, j, k)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO j=ny,1,-1
        txb(nxm, j, k) = ciwx6(nxm)*txb(nxm, j, k)
      END DO
    END DO
    DO i=nxm,2,-1
      DO k=nz,1,-1
        DO j=ny,1,-1
          txb(i-1, j, k) = txb(i-1, j, k) - cisx6(i)*txb(i, j, k)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO j=ny,1,-1
        uxb(nx, j, k) = uxb(nx, j, k) + aicix6*txb(nxm, j, k)
        uxb(nxm, j, k) = uxb(nxm, j, k) + (bicix6+aicix6)*txb(nxm, j, k)
        uxb(nxm-1, j, k) = uxb(nxm-1, j, k) + bicix6*txb(nxm, j, k)
        txb(nxm, j, k) = 0.0_8
        uxb(nxm, j, k) = uxb(nxm, j, k) + aicix6*txb(nxm-1, j, k)
        uxb(nxm-1, j, k) = uxb(nxm-1, j, k) + aicix6*txb(nxm-1, j, k)
        uxb(nx, j, k) = uxb(nx, j, k) + bicix6*txb(nxm-1, j, k)
        uxb(nxm-2, j, k) = uxb(nxm-2, j, k) + bicix6*txb(nxm-1, j, k)
        txb(nxm-1, j, k) = 0.0_8
      END DO
    END DO
    DO i=nxm-2,3,-1
      DO k=nz,1,-1
        DO j=ny,1,-1
          uxb(i+1, j, k) = uxb(i+1, j, k) + aicix6*txb(i, j, k)
          uxb(i, j, k) = uxb(i, j, k) + aicix6*txb(i, j, k)
          uxb(i+2, j, k) = uxb(i+2, j, k) + bicix6*txb(i, j, k)
          uxb(i-1, j, k) = uxb(i-1, j, k) + bicix6*txb(i, j, k)
          txb(i, j, k) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO j=ny,1,-1
        uxb(3, j, k) = uxb(3, j, k) + aicix6*txb(2, j, k)
        uxb(2, j, k) = uxb(2, j, k) + aicix6*txb(2, j, k)
        uxb(4, j, k) = uxb(4, j, k) + bicix6*txb(2, j, k)
        uxb(1, j, k) = uxb(1, j, k) + bicix6*txb(2, j, k)
        txb(2, j, k) = 0.0_8
        uxb(2, j, k) = uxb(2, j, k) + (bicix6+aicix6)*txb(1, j, k)
        uxb(1, j, k) = uxb(1, j, k) + aicix6*txb(1, j, k)
        uxb(3, j, k) = uxb(3, j, k) + bicix6*txb(1, j, k)
        txb(1, j, k) = 0.0_8
      END DO
    END DO
  END IF
END SUBROUTINE INTER6_B
