!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of intery16 in reverse (adjoint) mode:
!   gradient     of useful results: ty
!   with respect to varying inputs: uy
!
!********************************************************************
!
SUBROUTINE INTERY16_B(ty, tyb, uy, uyb, cify6, cisy6, ciwy6, nx, ny, nym&
&  , nz, npaire)
!-----------------------------------------------
!   M o d u l e s 
!-----------------------------------------------
  USE interpoly6_m 
  USE paramy_m 
  USE derivey_m 
  implicit none
!-----------------------------------------------
!   D u m m y   A r g u m e n t s
!-----------------------------------------------
  INTEGER, INTENT(IN) :: nx, ny, nym, nz, npaire
  REAL*8, INTENT(INOUT) :: ty(nx, nz, nym)
  REAL*8 :: tyb(nx, nz, nym)
  REAL*8, INTENT(IN) :: uy(nx, nz, ny)
  REAL*8 :: uyb(nx, nz, ny)
  REAL*8, INTENT(IN) :: cify6(nym)
  REAL*8, INTENT(IN) :: cisy6(nym)
  REAL*8, INTENT(IN) :: ciwy6(nym)
!-----------------------------------------------
!   L o c a l   V a r i a b l e s
!-----------------------------------------------
  INTEGER :: k, i, j
!-----------------------------------------------
!
!********************************************************************
!
  IF (npaire .EQ. 1) THEN
    DO j=1,nym-1,1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j+1) = tyb(i, k, j+1) - ciwy6(j)*cify6(j)*tyb(i, k, &
&            j)
          tyb(i, k, j) = ciwy6(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        tyb(i, k, nym) = ciwy6(nym)*tyb(i, k, nym)
      END DO
    END DO
    DO j=nym,2,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          tyb(i, k, j-1) = tyb(i, k, j-1) - cisy6(j)*tyb(i, k, j)
        END DO
      END DO
    END DO
    uyb = 0.0_8
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, ny) = uyb(i, k, ny) + aiciy6*tyb(i, k, nym)
        uyb(i, k, nym) = uyb(i, k, nym) + (biciy6+aiciy6)*tyb(i, k, nym)
        uyb(i, k, nym-1) = uyb(i, k, nym-1) + biciy6*tyb(i, k, nym)
        tyb(i, k, nym) = 0.0_8
        uyb(i, k, nym) = uyb(i, k, nym) + aiciy6*tyb(i, k, nym-1)
        uyb(i, k, nym-1) = uyb(i, k, nym-1) + aiciy6*tyb(i, k, nym-1)
        uyb(i, k, ny) = uyb(i, k, ny) + biciy6*tyb(i, k, nym-1)
        uyb(i, k, nym-2) = uyb(i, k, nym-2) + biciy6*tyb(i, k, nym-1)
        tyb(i, k, nym-1) = 0.0_8
      END DO
    END DO
    DO j=nym-2,3,-1
      DO k=nz,1,-1
        DO i=nx,1,-1
          uyb(i, k, j+1) = uyb(i, k, j+1) + aiciy6*tyb(i, k, j)
          uyb(i, k, j) = uyb(i, k, j) + aiciy6*tyb(i, k, j)
          uyb(i, k, j+2) = uyb(i, k, j+2) + biciy6*tyb(i, k, j)
          uyb(i, k, j-1) = uyb(i, k, j-1) + biciy6*tyb(i, k, j)
          tyb(i, k, j) = 0.0_8
        END DO
      END DO
    END DO
    DO k=nz,1,-1
      DO i=nx,1,-1
        uyb(i, k, 3) = uyb(i, k, 3) + aiciy6*tyb(i, k, 2)
        uyb(i, k, 2) = uyb(i, k, 2) + aiciy6*tyb(i, k, 2)
        uyb(i, k, 4) = uyb(i, k, 4) + biciy6*tyb(i, k, 2)
        uyb(i, k, 1) = uyb(i, k, 1) + biciy6*tyb(i, k, 2)
        tyb(i, k, 2) = 0.0_8
        uyb(i, k, 2) = uyb(i, k, 2) + (biciy6+aiciy6)*tyb(i, k, 1)
        uyb(i, k, 1) = uyb(i, k, 1) + aiciy6*tyb(i, k, 1)
        uyb(i, k, 3) = uyb(i, k, 3) + biciy6*tyb(i, k, 1)
        tyb(i, k, 1) = 0.0_8
      END DO
    END DO
  ELSE
    uyb = 0.0_8
  END IF
END SUBROUTINE INTERY16_B
