!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of prueba1 in reverse (adjoint) mode:
!   gradient     of useful results: u
!   with respect to varying inputs: u u0
!   RW status of diff variables: u:in-out u0:out
!
!******************************************************************
SUBROUTINE PRUEBA1_B(u0, u0b, u, ub, fenetrem, imodulob)
  IMPLICIT NONE
!
  INTEGER :: n, f, fenetrem, imodulob
  REAL*8 :: u0, utemp
  REAL*8 :: u0b, utempb
!
  REAL*8, DIMENSION(fenetrem) :: u
  REAL*8, DIMENSION(fenetrem) :: ub
  utempb = 0.0_8
  DO f=fenetrem,1,-1
    utempb = utempb + ub(f)
    ub(f) = 0.0_8
    DO n=imodulob,1,-1
      utempb = 3*utempb
    END DO
  END DO
  u0b = utempb
END SUBROUTINE PRUEBA1_B
