!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of prueba1 in forward (tangent) mode:
!   variations   of useful results: u
!   with respect to varying inputs: u0
!   RW status of diff variables: u:out u0:in
!
!******************************************************************
SUBROUTINE PRUEBA1_D(u0, u0d, u, ud, fenetrem, imodulob)
  IMPLICIT NONE
!
  INTEGER :: n, f, fenetrem, imodulob
  REAL*8 :: u0, utemp
  REAL*8 :: u0d, utempd
!
  REAL*8, DIMENSION(fenetrem) :: u
  REAL*8, DIMENSION(fenetrem) :: ud
  utempd = u0d
  utemp = u0
  ud = 0.0_8
  DO f=1,fenetrem
    DO n=1,imodulob
      utempd = 3*utempd
      utemp = 3*utemp
    END DO
    ud(f) = utempd
    u(f) = utemp
  END DO
  RETURN
END SUBROUTINE PRUEBA1_D
