!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.4 (r3342) - 27 Jan 2010 15:25
!
!  Differentiation of snorm in reverse (adjoint) mode:
!   gradient     of useful results: error
!   with respect to varying inputs: error uy0r by1r ux uy ux0r
!                bx1r
!   RW status of diff variables: error:in-zero uy0r:out by1r:out
!                ux:out uy:out ux0r:out bx1r:out
!
!  Entrada: wz, ux0r, uy0r, gx0r, gy0r, bx1r, by1r, errorb
!  Salida: wzb, ux0rb, uy0rb, gx0rb, gy0rb, bx1rb, by1rb
!  
!********************************************************************
!
SUBROUTINE SNORM_B(errorb, wz, wzb, wz_obsg, ux0r, ux0rb, uy0r, &
&  uy0rb, ux0r_obs, uy0r_obs, gx0r, gx0rb, gy0r, gy0rb, gx0r_obs, &
&  gy0r_obs, bx1r, bx1rb, by1r, by1rb, bx1_obs, by1_obs, fenetre, &
&  fenetrem, nx, ny, nz, nxr, nyr, nxrg, nyrg, jyt, rdxy, ditime, &
&  cov_obs, cov_iniu, cov_inig, cov_suav, cov_tay, cov_gau, jw, iw, w_xy, &
&  sumw_xy, n_nodos, n_nodos_max, jwq, iwq, w_xyq, sumw_xyq, n_nodos_q, &
&  n_nodos_q_max, itw, w_t, sumw_t, n_nodos_t, n_nodos_t_max, &
&  i_redg1, i_redg2, j_redg1, j_redg2, nxrg_asim, nyrg_asim)
!
  implicit none
!
  INTEGER :: f, fenetre, fenetrem, nx, ny, nz
  INTEGER :: j_redg, i_redg, nxrg, nyrg, nxyrg, jyt, rdxy, ditime
  INTEGER :: j_redg1, j_redg2, i_redg1, i_redg2, nxrg_asim, nyrg_asim, nxyrg_asim
!
  REAL*8, DIMENSION(fenetre, nxrg, nyrg, nz) :: wz_obsg
  REAL*8, DIMENSION(fenetrem, nxrg, nyrg, nz) :: wz_av
  REAL*8, DIMENSION(fenetrem, nxrg, nyrg, nz) :: wz_avb
  REAL*8, DIMENSION(fenetrem, nx, ny, nz) :: wz
  REAL*8, DIMENSION(fenetrem, nx, ny, nz) :: wzb
  INTEGER :: j_red, i_red, nxr, nyr, nxyr, j_rec, i_rec, j, i
  REAL*8, DIMENSION(nxr, nyr, nz) :: ux0r, uy0r, gx0r, gy0r
  REAL*8, DIMENSION(nxr, nyr, nz) :: ux0rb, uy0rb, gx0rb, gy0rb
  REAL*8, DIMENSION(nxr, nyr, nz) :: ux0r_av, uy0r_av
  REAL*8, DIMENSION(nxr, nyr, nz) :: ux0r_avb, uy0r_avb
  REAL*8, DIMENSION(nxr, nyr, nz) :: ux0r_obs, uy0r_obs, gx0r_obs, gy0r_obs
  REAL*8, DIMENSION(nyr, ditime) :: bx1r, by1r, bx1r_av, by1r_av
  REAL*8, DIMENSION(nyr, ditime) :: bx1rb, by1rb, bx1r_avb, by1r_avb
  REAL*8, DIMENSION(nyr, ditime) :: bx1_obs, by1_obs
  REAL*8, DIMENSION(nxrg, nyrg) :: errorm
  REAL*8, DIMENSION(nxrg, nyrg) :: errormb
  REAL*8, DIMENSION(nxr, nyr) :: errorlu, errorlg, errormq
  REAL*8, DIMENSION(nxr, nyr) :: errorlub, errorlgb, errormqb
  REAL*8, DIMENSION(nyr) :: errorp
  REAL*8, DIMENSION(nyr) :: errorpb
  REAL*8, DIMENSION(ditime) :: errorq
  REAL*8, DIMENSION(ditime) :: errorqb
  REAL*8, DIMENSION(fenetrem) :: errorv
  REAL*8, DIMENSION(fenetrem) :: errorvb
  REAL*8, DIMENSION(nyr) :: errorn
  REAL*8, DIMENSION(nyr) :: errornb
  REAL*8, DIMENSION(ditime) :: errorw
  REAL*8, DIMENSION(ditime) :: errorwb
  INTEGER :: itime, n_nodos_max, n_nodos_q_max, n_nodos_t_max, nodo
  INTEGER, DIMENSION(nxrg, nyrg, n_nodos_max) :: iw, jw
  REAL*8, DIMENSION(nxrg, nyrg, n_nodos_max) :: w_xy
  INTEGER, DIMENSION(nxrg, nyrg) :: n_nodos
  REAL*8, DIMENSION(nxrg, nyrg) :: sumw_xy
  REAL*8, DIMENSION(n_nodos_max) :: wwz
  REAL*8, DIMENSION(n_nodos_max) :: wwzb
  INTEGER, DIMENSION(nxr, nyr, n_nodos_q_max) :: iwq, jwq
  REAL*8, DIMENSION(nxr, nyr, n_nodos_q_max) :: w_xyq
  INTEGER, DIMENSION(nxr, nyr) :: n_nodos_q
  REAL*8, DIMENSION(nxr, nyr) :: sumw_xyq
  REAL*8, DIMENSION(n_nodos_q_max) :: wux, wuy
  REAL*8, DIMENSION(n_nodos_q_max) :: wuxb, wuyb
  INTEGER, DIMENSION(ditime, n_nodos_t_max) :: itw
  REAL*8, DIMENSION(ditime, n_nodos_t_max) :: w_t
  INTEGER, DIMENSION(ditime) :: n_nodos_t
  REAL*8, DIMENSION(ditime) :: sumw_t
  REAL*8, DIMENSION(n_nodos_t_max) :: wbx1r, wby1r
  REAL*8, DIMENSION(n_nodos_t_max) :: wbx1rb, wby1rb
  REAL*8 :: deltwz_obs
  REAL*8 :: deltwz_obsb
  REAL*8 :: deltux_ini, deltuy_ini, deltgx_ini, deltgy_ini
  REAL*8 :: deltux_inib, deltuy_inib, deltgx_inib, deltgy_inib
  REAL*8 :: deltux_suav, deltuy_suav
  REAL*8 :: deltux_suavb, deltuy_suavb
  REAL*8 :: deltux_tay, deltuy_tay, deltux_gau, deltuy_gau
  REAL*8 :: deltux_tayb, deltuy_tayb, deltux_gaub, deltuy_gaub
  REAL*8 :: error, error_obs, error_iniu, error_inig, error_suav, error_tay, error_gau
  REAL*8 :: errorb, error_obsb, error_iniub, error_inigb, error_suavb, error_tayb, error_gaub
  REAL*8 :: cov_obs, cov_iniu, cov_inig, cov_suav, cov_tay, cov_gau
  REAL*8 :: w_r, sumw_r, w_q, sumw_q, w_d, sumw_d
!
  nxyr = nxr*nyr
  nxyrg = nxrg*nyrg
  nxyrg_asim = nxrg_asim*nyrg_asim
!
! *****************************************************************
! ************************* Forward sweep *************************
! *****************************************************************
!
! ********************* error_obs *********************
  do f=1,fenetrem
!
  do j_redg = j_redg1,j_redg2
  do i_redg = i_redg1,i_redg2
!
!    /w_r(nodo)*wz_r(nodo)
     wwz=0.
     do nodo=1,n_nodos(i_redg,j_redg)
        i=iw(i_redg,j_redg,nodo)
        j=jw(i_redg,j_redg,nodo)
        w_r=w_xy(i_redg,j_redg,nodo)
        wwz(nodo) = w_r*wz(f,i,j,1)
     enddo
!
!    Weighted average
     sumw_r=sumw_xy(i_redg,j_redg)
     wz_av(f,i_redg,j_redg,1) = sum(wwz)/sumw_r
  enddo
  enddo 
!
  enddo 
! 
! ********************* error_suav *********************
  do j_red=1,nyr
  do i_red=1,nxr
!
!    /w_r(nodo)*u_r(nodo)
     wux=0. ; wuy=0.
     do nodo=1,n_nodos_q(i_red,j_red)
        i=iwq(i_red,j_red,nodo)
        j=jwq(i_red,j_red,nodo)
        w_q=w_xyq(i_red,j_red,nodo)
        wux(nodo) = w_q*ux0r(i,j,1)
        wuy(nodo) = w_q*uy0r(i,j,1)
     enddo
!
!    Weighted average
     sumw_q=sumw_xyq(i_red,j_red)
     ux0r_av(i_red,j_red,1) = sum(wux)/sumw_q
     uy0r_av(i_red,j_red,1) = sum(wuy)/sumw_q
  enddo
  enddo 
! 
! ********************* error_gau *********************
  do itime=1,ditime
  do j=1,nyr
!
!    /w_t(nodo)*b1r_t(nodo)
     wbx1r=0.
     wby1r=0.
     do nodo=1,n_nodos_t(itime)
        i=itw(itime,nodo)
        w_d=w_t(itime,nodo)
        wbx1r(nodo) = w_d*bx1r(j,i)
        wby1r(nodo) = w_d*by1r(j,i)
     enddo
!
!    Weighted average
     sumw_d=sumw_t(itime)
     bx1r_av(j,itime) = sum(wbx1r)/sumw_d
     by1r_av(j,itime) = sum(wby1r)/sumw_d
  enddo
  enddo 
!
! ******************************************************************
! ************************* Backward sweep *************************
! ******************************************************************
!
! ********************* error_gau *********************
  error_gaub = errorb
  errorqb = 0.0_8
  errorqb = error_gaub/ditime
  bx1r_avb = 0.0_8
  by1r_avb = 0.0_8
  bx1rb = 0.0_8
  by1rb = 0.0_8
  errorpb = 0.0_8
!
  DO itime=ditime,1,-1
!
    errorpb = errorpb + errorqb(itime)/nyr
    errorqb(itime) = 0.0_8
!
    DO j=nyr,1,-1
      deltux_gau = bx1r(j, itime) - bx1r_av(j, itime)
      deltuy_gau = by1r(j, itime) - by1r_av(j, itime)
      deltux_gaub = cov_gau*2*deltux_gau*errorpb(j)
      deltuy_gaub = cov_gau*2*deltuy_gau*errorpb(j)
      errorpb(j) = 0.0_8
      by1rb(j, itime) = by1rb(j, itime) + deltuy_gaub
      by1r_avb(j, itime) = by1r_avb(j, itime) - deltuy_gaub
      bx1rb(j, itime) = bx1rb(j, itime) + deltux_gaub
      bx1r_avb(j, itime) = bx1r_avb(j, itime) - deltux_gaub
      sumw_d = sumw_t(itime)
      wby1rb = 0.0_8
      wby1rb = by1r_avb(j, itime)/sumw_d
      by1r_avb(j, itime) = 0.0_8
      wbx1rb = 0.0_8
      wbx1rb = bx1r_avb(j, itime)/sumw_d
      bx1r_avb(j, itime) = 0.0_8
!
      DO nodo=n_nodos_t(itime),1,-1
        w_d = w_t(itime, nodo)
        i = itw(itime, nodo)
        by1rb(j, i) = by1rb(j, i) + w_d*wby1rb(nodo)
        wby1rb(nodo) = 0.0_8
        bx1rb(j, i) = bx1rb(j, i) + w_d*wbx1rb(nodo)
        wbx1rb(nodo) = 0.0_8
      END DO
!
    END DO
!
  END DO
!
! ********************* error_tay *********************
  error_tayb = errorb
  errorwb = 0.0_8
  errorwb = error_tayb/ditime
  errornb = 0.0_8
!
  DO itime=ditime,1,-1
!
    errornb = errornb + errorwb(itime)/nyr
    errorwb(itime) = 0.0_8
!
    DO j=nyr,1,-1
      deltux_tay = bx1r(j, itime) - bx1_obs(j, itime)
      deltuy_tay = by1r(j, itime) - by1_obs(j, itime)
      deltux_tayb = cov_tay*2*deltux_tay*errornb(j)
      deltuy_tayb = cov_tay*2*deltuy_tay*errornb(j)
      errornb(j) = 0.0_8
      by1rb(j, itime) = by1rb(j, itime) + deltuy_tayb
      bx1rb(j, itime) = bx1rb(j, itime) + deltux_tayb
    END DO
!
  END DO
!
! ********************* error_suav *********************
  error_suavb = errorb
  errormqb = 0.0_8
  errormqb = error_suavb/nxyr
  ux0r_avb = 0.0_8
  uy0r_avb = 0.0_8
  ux0rb = 0.0_8
  uy0rb = 0.0_8
!
  DO j_red=nyr,1,-1
    DO i_red=nxr,1,-1
      deltuy_suav = uy0r(i_red, j_red, 1) - uy0r_av(i_red, j_red, 1)
      deltux_suav = ux0r(i_red, j_red, 1) - ux0r_av(i_red, j_red, 1)
      deltux_suavb = cov_suav*2*deltux_suav*errormqb(i_red, j_red)
      deltuy_suavb = cov_suav*2*deltuy_suav*errormqb(i_red, j_red)
      errormqb(i_red, j_red) = 0.0_8
      uy0rb(i_red, j_red, 1) = uy0rb(i_red, j_red, 1) + deltuy_suavb
      uy0r_avb(i_red, j_red, 1) = uy0r_avb(i_red, j_red, 1) - deltuy_suavb
      ux0rb(i_red, j_red, 1) = ux0rb(i_red, j_red, 1) + deltux_suavb
      ux0r_avb(i_red, j_red, 1) = ux0r_avb(i_red, j_red, 1) - deltux_suavb
      sumw_q = sumw_xyq(i_red, j_red)
      wuyb = 0.0_8
      wuyb = uy0r_avb(i_red, j_red, 1)/sumw_q
      uy0r_avb(i_red, j_red, 1) = 0.0_8
      wuxb = 0.0_8
      wuxb = ux0r_avb(i_red, j_red, 1)/sumw_q
      ux0r_avb(i_red, j_red, 1) = 0.0_8
!
      DO nodo=n_nodos_q(i_red,j_red),1,-1
        i = iwq(i_red, j_red, nodo)
        j = jwq(i_red, j_red, nodo)
        w_q = w_xyq(i_red, j_red, nodo)
        uy0rb(i, j, 1) = uy0rb(i, j, 1) + w_q*wuyb(nodo)
        wuyb(nodo) = 0.0_8
        ux0rb(i, j, 1) = ux0rb(i, j, 1) + w_q*wuxb(nodo)
        wuxb(nodo) = 0.0_8
      END DO
!
    END DO
  END DO
! 
! ********************* error_inig *********************
  error_inigb = errorb
  errorlgb = 0.0_8
  errorlgb = error_inigb/nxyr
  gy0rb = 0.0_8
  gx0rb = 0.0_8
!
  DO j=nyr,1,-1
    DO i=nxr,1,-1
      deltgx_ini = gx0r(i, j, 1) - gx0r_obs(i, j, 1)
      deltgy_ini = gy0r(i, j, 1) - gy0r_obs(i, j, 1)
      deltgx_inib = cov_inig*2*deltgx_ini*errorlgb(i, j)
      deltgy_inib = cov_inig*2*deltgy_ini*errorlgb(i, j)
      errorlgb(i, j) = 0.0_8
      gy0rb(i, j, 1) = gy0rb(i, j, 1) + deltgy_inib
      gx0rb(i, j, 1) = gx0rb(i, j, 1) + deltgx_inib
    END DO
  END DO
!
! ********************* error_iniu *********************
  error_iniub = errorb
  errorlub = 0.0_8
  errorlub = error_iniub/nxyr
!
  DO j=nyr,1,-1
    DO i=nxr,1,-1
      deltux_ini = ux0r(i, j, 1) - ux0r_obs(i, j, 1)
      deltuy_ini = uy0r(i, j, 1) - uy0r_obs(i, j, 1)
      deltux_inib = cov_iniu*2*deltux_ini*errorlub(i, j)
      deltuy_inib = cov_iniu*2*deltuy_ini*errorlub(i, j)
      errorlub(i, j) = 0.0_8
      uy0rb(i, j, 1) = uy0rb(i, j, 1) + deltuy_inib
      ux0rb(i, j, 1) = ux0rb(i, j, 1) + deltux_inib
    END DO
  END DO
! 
! ********************* error_obs *********************
  error_obsb = errorb
  errorvb = 0.0_8
  errorvb = error_obsb/fenetrem
  wz_avb = 0.0_8
  wzb = 0.0_8
  errormb = 0.0_8
!
  DO f=fenetrem,1,-1
!
    errormb = errormb + errorvb(f)/nxyrg_asim
    errorvb(f) = 0.0_8
!
    DO j_redg=j_redg2,j_redg1,-1
      DO i_redg=i_redg2,i_redg1,-1
        deltwz_obs = wz_av(f, i_redg, j_redg, 1) - wz_obsg(f+1, i_redg, j_redg, 1)
        deltwz_obsb = cov_obs*2*deltwz_obs*errormb(i_redg, j_redg)
        errormb(i_redg, j_redg) = 0.0_8
        wz_avb(f, i_redg, j_redg, 1) = wz_avb(f, i_redg, j_redg, 1) + deltwz_obsb
        sumw_r = sumw_xy(i_redg, j_redg)
        wwzb = 0.0_8
        wwzb = wz_avb(f, i_redg, j_redg, 1)/sumw_r
        wz_avb(f, i_redg, j_redg, 1) = 0.0_8
!
        DO nodo=n_nodos(i_redg,j_redg),1,-1
          i = iw(i_redg, j_redg, nodo)
          j = jw(i_redg, j_redg, nodo)
          w_r = w_xy(i_redg, j_redg, nodo)
          wzb(f, i, j, 1) = wzb(f, i, j, 1) + w_r*wwzb(nodo)
          wwzb(nodo) = 0.0_8
        END DO
!
      END DO
    END DO
!
  END DO
!
END SUBROUTINE SNORM_B
